/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ListOrganizationRepositoriesResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ListOrganizationRepositoriesResponseFromJSON,
    ListOrganizationRepositoriesResponseToJSON,
} from '../models/index';

export interface ListOrganizationRepositoriesRequest {
    orgSlug: string;
    orgId?: string;
    pageSize?: string;
    pageToken?: string;
}

export interface ListOrganizationRepositoriesByIDRequest {
    orgId: string;
    pageSize?: string;
    pageToken?: string;
}

/**
 * 
 */
export class OrganizationApi extends runtime.BaseAPI {

    /**
     * List Organization Repositories
     */
    async listOrganizationRepositoriesRaw(requestParameters: ListOrganizationRepositoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOrganizationRepositoriesResponse>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling listOrganizationRepositories().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['org_id'] = requestParameters['orgId'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/{org_slug}/repos`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListOrganizationRepositoriesResponseFromJSON(jsonValue));
    }

    /**
     * List Organization Repositories
     */
    async listOrganizationRepositories(requestParameters: ListOrganizationRepositoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOrganizationRepositoriesResponse> {
        const response = await this.listOrganizationRepositoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Organization Repositories (By Organization ID)
     */
    async listOrganizationRepositoriesByIDRaw(requestParameters: ListOrganizationRepositoriesByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListOrganizationRepositoriesResponse>> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling listOrganizationRepositoriesByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orgs/id:{org_id}/repos`;
        urlPath = urlPath.replace(`{${"org_id"}}`, encodeURIComponent(String(requestParameters['orgId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListOrganizationRepositoriesResponseFromJSON(jsonValue));
    }

    /**
     * List Organization Repositories (By Organization ID)
     */
    async listOrganizationRepositoriesByID(requestParameters: ListOrganizationRepositoriesByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListOrganizationRepositoriesResponse> {
        const response = await this.listOrganizationRepositoriesByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
