/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiErrorResponse, ReleaseAsset } from "../models/index";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ReleaseAssetFromJSON,
    ReleaseAssetToJSON,
} from "../models/index";

export interface AddReleaseAssetAttachmentRequest {
    orgSlug: string;
    repoSlug: string;
    releaseTag: string;
    file: Blob;
    name: string;
}

export interface AddReleaseAssetAttachmentByIDRequest {
    releaseId: string;
    file: Blob;
}

/**
 * ReleaseAttachmentsApi - interface
 *
 * @export
 * @interface ReleaseAttachmentsApiInterface
 */
export interface ReleaseAttachmentsApiInterface {
    /**
     * Uploads attachment to a release and adds it as an asset
     * @summary Upload Attachment As Release Asset (By Release Tag)
     * @param {string} orgSlug
     * @param {string} repoSlug
     * @param {string} releaseTag
     * @param {Blob} file The file to upload
     * @param {string} name The intended name of the asset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleaseAttachmentsApiInterface
     */
    addReleaseAssetAttachmentRaw(
        requestParameters: AddReleaseAssetAttachmentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ReleaseAsset>>;

    /**
     * Uploads attachment to a release and adds it as an asset
     * Upload Attachment As Release Asset (By Release Tag)
     */
    addReleaseAssetAttachment(
        requestParameters: AddReleaseAssetAttachmentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ReleaseAsset>;

    /**
     * Uploads attachment to a release and adds it as an asset
     * @summary Upload Attachment As Release Asset (By Release ID)
     * @param {string} releaseId
     * @param {Blob} file The file to upload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleaseAttachmentsApiInterface
     */
    addReleaseAssetAttachmentByIDRaw(
        requestParameters: AddReleaseAssetAttachmentByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ReleaseAsset>>;

    /**
     * Uploads attachment to a release and adds it as an asset
     * Upload Attachment As Release Asset (By Release ID)
     */
    addReleaseAssetAttachmentByID(
        requestParameters: AddReleaseAssetAttachmentByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ReleaseAsset>;
}

/**
 *
 */
export class ReleaseAttachmentsApi
    extends runtime.BaseAPI
    implements ReleaseAttachmentsApiInterface
{
    /**
     * Uploads attachment to a release and adds it as an asset
     * Upload Attachment As Release Asset (By Release Tag)
     */
    async addReleaseAssetAttachmentRaw(
        requestParameters: AddReleaseAssetAttachmentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ReleaseAsset>> {
        if (requestParameters["orgSlug"] == null) {
            throw new runtime.RequiredError(
                "orgSlug",
                'Required parameter "orgSlug" was null or undefined when calling addReleaseAssetAttachment().'
            );
        }

        if (requestParameters["repoSlug"] == null) {
            throw new runtime.RequiredError(
                "repoSlug",
                'Required parameter "repoSlug" was null or undefined when calling addReleaseAssetAttachment().'
            );
        }

        if (requestParameters["releaseTag"] == null) {
            throw new runtime.RequiredError(
                "releaseTag",
                'Required parameter "releaseTag" was null or undefined when calling addReleaseAssetAttachment().'
            );
        }

        if (requestParameters["file"] == null) {
            throw new runtime.RequiredError(
                "file",
                'Required parameter "file" was null or undefined when calling addReleaseAssetAttachment().'
            );
        }

        if (requestParameters["name"] == null) {
            throw new runtime.RequiredError(
                "name",
                'Required parameter "name" was null or undefined when calling addReleaseAssetAttachment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters["file"] != null) {
            formParams.append("file", requestParameters["file"] as any);
        }

        if (requestParameters["name"] != null) {
            formParams.append("name", requestParameters["name"] as any);
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/releases/tag/{release_tag}/attachments`;
        urlPath = urlPath.replace(
            `{${"org_slug"}}`,
            encodeURIComponent(String(requestParameters["orgSlug"]))
        );
        urlPath = urlPath.replace(
            `{${"repo_slug"}}`,
            encodeURIComponent(String(requestParameters["repoSlug"]))
        );
        urlPath = urlPath.replace(
            `{${"release_tag"}}`,
            encodeURIComponent(String(requestParameters["releaseTag"]))
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: formParams,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ReleaseAssetFromJSON(jsonValue)
        );
    }

    /**
     * Uploads attachment to a release and adds it as an asset
     * Upload Attachment As Release Asset (By Release Tag)
     */
    async addReleaseAssetAttachment(
        requestParameters: AddReleaseAssetAttachmentRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ReleaseAsset> {
        const response = await this.addReleaseAssetAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Uploads attachment to a release and adds it as an asset
     * Upload Attachment As Release Asset (By Release ID)
     */
    async addReleaseAssetAttachmentByIDRaw(
        requestParameters: AddReleaseAssetAttachmentByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ReleaseAsset>> {
        if (requestParameters["releaseId"] == null) {
            throw new runtime.RequiredError(
                "releaseId",
                'Required parameter "releaseId" was null or undefined when calling addReleaseAssetAttachmentByID().'
            );
        }

        if (requestParameters["file"] == null) {
            throw new runtime.RequiredError(
                "file",
                'Required parameter "file" was null or undefined when calling addReleaseAssetAttachmentByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [{ contentType: "multipart/form-data" }];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters["file"] != null) {
            formParams.append("file", requestParameters["file"] as any);
        }

        let urlPath = `/releases/id:{release_id}/attachments`;
        urlPath = urlPath.replace(
            `{${"release_id"}}`,
            encodeURIComponent(String(requestParameters["releaseId"]))
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: formParams,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ReleaseAssetFromJSON(jsonValue)
        );
    }

    /**
     * Uploads attachment to a release and adds it as an asset
     * Upload Attachment As Release Asset (By Release ID)
     */
    async addReleaseAssetAttachmentByID(
        requestParameters: AddReleaseAssetAttachmentByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ReleaseAsset> {
        const response = await this.addReleaseAssetAttachmentByIDRaw(
            requestParameters,
            initOverrides
        );
        return await response.value();
    }
}
