/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CreatePullRequestBody,
  ListRepositoryPullRequestsResponse,
  PullRequest,
  UpdatePullRequestBody,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CreatePullRequestBodyFromJSON,
    CreatePullRequestBodyToJSON,
    ListRepositoryPullRequestsResponseFromJSON,
    ListRepositoryPullRequestsResponseToJSON,
    PullRequestFromJSON,
    PullRequestToJSON,
    UpdatePullRequestBodyFromJSON,
    UpdatePullRequestBodyToJSON,
} from '../models/index';

export interface CreatePullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    createPullRequestBody: CreatePullRequestBody;
    silent?: boolean;
}

export interface CreatePullRequestByIDRequest {
    repoId: string;
    createPullRequestBody: CreatePullRequestBody;
    silent?: boolean;
}

export interface DiscardPullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    pullRequestSlug: string;
    pullRequestId?: string;
    silent?: boolean;
}

export interface DiscardPullRequestByIDRequest {
    pullRequestId: string;
    pullRequestSlug?: string;
    silent?: boolean;
}

export interface DraftPullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    pullRequestSlug: string;
    pullRequestId?: string;
    silent?: boolean;
}

export interface DraftPullRequestByIDRequest {
    pullRequestId: string;
    pullRequestSlug?: string;
    silent?: boolean;
}

export interface GetPullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    pullRequestSlug: string;
    pullRequestId?: string;
}

export interface GetPullRequestByIDRequest {
    pullRequestId: string;
    pullRequestSlug?: string;
}

export interface ListRepositoryPullRequestsRequest {
    orgSlug: string;
    repoSlug: string;
    pageSize?: string;
    pageToken?: string;
    sortBy?: string;
}

export interface ListRepositoryPullRequestsByIDRequest {
    repoId: string;
    pageSize?: string;
    pageToken?: string;
    sortBy?: string;
}

export interface PublishPullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    pullRequestSlug: string;
    pullRequestId?: string;
    silent?: boolean;
}

export interface PublishPullRequestByIDRequest {
    pullRequestId: string;
    pullRequestSlug?: string;
    silent?: boolean;
}

export interface ReopenPullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    pullRequestSlug: string;
    pullRequestId?: string;
    silent?: boolean;
}

export interface ReopenPullRequestByIDRequest {
    pullRequestId: string;
    pullRequestSlug?: string;
    silent?: boolean;
}

export interface UpdatePullRequestRequest {
    orgSlug: string;
    repoSlug: string;
    pullRequestSlug: string;
    updatePullRequestBody: UpdatePullRequestBody;
    pullRequestId?: string;
    silent?: boolean;
}

export interface UpdatePullRequestByIDRequest {
    pullRequestId: string;
    updatePullRequestBody: UpdatePullRequestBody;
    pullRequestSlug?: string;
    silent?: boolean;
}

/**
 * 
 */
export class RepositoryPullRequestApi extends runtime.BaseAPI {

    /**
     * Create PullRequest in Repository
     */
    async createPullRequestRaw(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling createPullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling createPullRequest().'
            );
        }

        if (requestParameters['createPullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'createPullRequestBody',
                'Required parameter "createPullRequestBody" was null or undefined when calling createPullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePullRequestBodyToJSON(requestParameters['createPullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Create PullRequest in Repository
     */
    async createPullRequest(requestParameters: CreatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.createPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create PullRequest in Repository (By Repo ID)
     */
    async createPullRequestByIDRaw(requestParameters: CreatePullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['repoId'] == null) {
            throw new runtime.RequiredError(
                'repoId',
                'Required parameter "repoId" was null or undefined when calling createPullRequestByID().'
            );
        }

        if (requestParameters['createPullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'createPullRequestBody',
                'Required parameter "createPullRequestBody" was null or undefined when calling createPullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/id:{repo_id}/pulls`;
        urlPath = urlPath.replace(`{${"repo_id"}}`, encodeURIComponent(String(requestParameters['repoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePullRequestBodyToJSON(requestParameters['createPullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Create PullRequest in Repository (By Repo ID)
     */
    async createPullRequestByID(requestParameters: CreatePullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.createPullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Discard PullRequest
     */
    async discardPullRequestRaw(requestParameters: DiscardPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling discardPullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling discardPullRequest().'
            );
        }

        if (requestParameters['pullRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'pullRequestSlug',
                'Required parameter "pullRequestSlug" was null or undefined when calling discardPullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestId'] != null) {
            queryParameters['pull_request_id'] = requestParameters['pullRequestId'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls/{pull_request_slug}/discard`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"pull_request_slug"}}`, encodeURIComponent(String(requestParameters['pullRequestSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Discard PullRequest
     */
    async discardPullRequest(requestParameters: DiscardPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.discardPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Discard PullRequest (By ID)
     */
    async discardPullRequestByIDRaw(requestParameters: DiscardPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['pullRequestId'] == null) {
            throw new runtime.RequiredError(
                'pullRequestId',
                'Required parameter "pullRequestId" was null or undefined when calling discardPullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestSlug'] != null) {
            queryParameters['pull_request_slug'] = requestParameters['pullRequestSlug'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pulls/id:{pull_request_id}/discard`;
        urlPath = urlPath.replace(`{${"pull_request_id"}}`, encodeURIComponent(String(requestParameters['pullRequestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Discard PullRequest (By ID)
     */
    async discardPullRequestByID(requestParameters: DiscardPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.discardPullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Draft PullRequest
     */
    async draftPullRequestRaw(requestParameters: DraftPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling draftPullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling draftPullRequest().'
            );
        }

        if (requestParameters['pullRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'pullRequestSlug',
                'Required parameter "pullRequestSlug" was null or undefined when calling draftPullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestId'] != null) {
            queryParameters['pull_request_id'] = requestParameters['pullRequestId'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls/{pull_request_slug}/draft`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"pull_request_slug"}}`, encodeURIComponent(String(requestParameters['pullRequestSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Draft PullRequest
     */
    async draftPullRequest(requestParameters: DraftPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.draftPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Draft PullRequest (By ID)
     */
    async draftPullRequestByIDRaw(requestParameters: DraftPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['pullRequestId'] == null) {
            throw new runtime.RequiredError(
                'pullRequestId',
                'Required parameter "pullRequestId" was null or undefined when calling draftPullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestSlug'] != null) {
            queryParameters['pull_request_slug'] = requestParameters['pullRequestSlug'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pulls/id:{pull_request_id}/draft`;
        urlPath = urlPath.replace(`{${"pull_request_id"}}`, encodeURIComponent(String(requestParameters['pullRequestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Draft PullRequest (By ID)
     */
    async draftPullRequestByID(requestParameters: DraftPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.draftPullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get PullRequest
     */
    async getPullRequestRaw(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling getPullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling getPullRequest().'
            );
        }

        if (requestParameters['pullRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'pullRequestSlug',
                'Required parameter "pullRequestSlug" was null or undefined when calling getPullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestId'] != null) {
            queryParameters['pull_request_id'] = requestParameters['pullRequestId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls/{pull_request_slug}`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"pull_request_slug"}}`, encodeURIComponent(String(requestParameters['pullRequestSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Get PullRequest
     */
    async getPullRequest(requestParameters: GetPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.getPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get PullRequest (By ID)
     */
    async getPullRequestByIDRaw(requestParameters: GetPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['pullRequestId'] == null) {
            throw new runtime.RequiredError(
                'pullRequestId',
                'Required parameter "pullRequestId" was null or undefined when calling getPullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestSlug'] != null) {
            queryParameters['pull_request_slug'] = requestParameters['pullRequestSlug'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pulls/id:{pull_request_id}`;
        urlPath = urlPath.replace(`{${"pull_request_id"}}`, encodeURIComponent(String(requestParameters['pullRequestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Get PullRequest (By ID)
     */
    async getPullRequestByID(requestParameters: GetPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.getPullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all pull requests from an repository
     * List Repository Pull Requests
     */
    async listRepositoryPullRequestsRaw(requestParameters: ListRepositoryPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRepositoryPullRequestsResponse>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling listRepositoryPullRequests().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling listRepositoryPullRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRepositoryPullRequestsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all pull requests from an repository
     * List Repository Pull Requests
     */
    async listRepositoryPullRequests(requestParameters: ListRepositoryPullRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRepositoryPullRequestsResponse> {
        const response = await this.listRepositoryPullRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves all pull requests from an repository
     * List Repository Pull Requests (By Repo ID)
     */
    async listRepositoryPullRequestsByIDRaw(requestParameters: ListRepositoryPullRequestsByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRepositoryPullRequestsResponse>> {
        if (requestParameters['repoId'] == null) {
            throw new runtime.RequiredError(
                'repoId',
                'Required parameter "repoId" was null or undefined when calling listRepositoryPullRequestsByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/id:{repo_id}/pulls`;
        urlPath = urlPath.replace(`{${"repo_id"}}`, encodeURIComponent(String(requestParameters['repoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRepositoryPullRequestsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all pull requests from an repository
     * List Repository Pull Requests (By Repo ID)
     */
    async listRepositoryPullRequestsByID(requestParameters: ListRepositoryPullRequestsByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRepositoryPullRequestsResponse> {
        const response = await this.listRepositoryPullRequestsByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish PullRequest (change status to open)
     */
    async publishPullRequestRaw(requestParameters: PublishPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling publishPullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling publishPullRequest().'
            );
        }

        if (requestParameters['pullRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'pullRequestSlug',
                'Required parameter "pullRequestSlug" was null or undefined when calling publishPullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestId'] != null) {
            queryParameters['pull_request_id'] = requestParameters['pullRequestId'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls/{pull_request_slug}/publish`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"pull_request_slug"}}`, encodeURIComponent(String(requestParameters['pullRequestSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Publish PullRequest (change status to open)
     */
    async publishPullRequest(requestParameters: PublishPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.publishPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish PullRequest (By ID)
     */
    async publishPullRequestByIDRaw(requestParameters: PublishPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['pullRequestId'] == null) {
            throw new runtime.RequiredError(
                'pullRequestId',
                'Required parameter "pullRequestId" was null or undefined when calling publishPullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestSlug'] != null) {
            queryParameters['pull_request_slug'] = requestParameters['pullRequestSlug'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pulls/id:{pull_request_id}/publish`;
        urlPath = urlPath.replace(`{${"pull_request_id"}}`, encodeURIComponent(String(requestParameters['pullRequestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Publish PullRequest (By ID)
     */
    async publishPullRequestByID(requestParameters: PublishPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.publishPullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reopen PullRequest
     */
    async reopenPullRequestRaw(requestParameters: ReopenPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling reopenPullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling reopenPullRequest().'
            );
        }

        if (requestParameters['pullRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'pullRequestSlug',
                'Required parameter "pullRequestSlug" was null or undefined when calling reopenPullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestId'] != null) {
            queryParameters['pull_request_id'] = requestParameters['pullRequestId'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls/{pull_request_slug}/reopen`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"pull_request_slug"}}`, encodeURIComponent(String(requestParameters['pullRequestSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Reopen PullRequest
     */
    async reopenPullRequest(requestParameters: ReopenPullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.reopenPullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reopen PullRequest (By ID)
     */
    async reopenPullRequestByIDRaw(requestParameters: ReopenPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['pullRequestId'] == null) {
            throw new runtime.RequiredError(
                'pullRequestId',
                'Required parameter "pullRequestId" was null or undefined when calling reopenPullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestSlug'] != null) {
            queryParameters['pull_request_slug'] = requestParameters['pullRequestSlug'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pulls/id:{pull_request_id}/reopen`;
        urlPath = urlPath.replace(`{${"pull_request_id"}}`, encodeURIComponent(String(requestParameters['pullRequestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Reopen PullRequest (By ID)
     */
    async reopenPullRequestByID(requestParameters: ReopenPullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.reopenPullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update PullRequest
     */
    async updatePullRequestRaw(requestParameters: UpdatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling updatePullRequest().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling updatePullRequest().'
            );
        }

        if (requestParameters['pullRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'pullRequestSlug',
                'Required parameter "pullRequestSlug" was null or undefined when calling updatePullRequest().'
            );
        }

        if (requestParameters['updatePullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'updatePullRequestBody',
                'Required parameter "updatePullRequestBody" was null or undefined when calling updatePullRequest().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestId'] != null) {
            queryParameters['pull_request_id'] = requestParameters['pullRequestId'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/pulls/{pull_request_slug}`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"pull_request_slug"}}`, encodeURIComponent(String(requestParameters['pullRequestSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePullRequestBodyToJSON(requestParameters['updatePullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Update PullRequest
     */
    async updatePullRequest(requestParameters: UpdatePullRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.updatePullRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update PullRequest (By ID)
     */
    async updatePullRequestByIDRaw(requestParameters: UpdatePullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PullRequest>> {
        if (requestParameters['pullRequestId'] == null) {
            throw new runtime.RequiredError(
                'pullRequestId',
                'Required parameter "pullRequestId" was null or undefined when calling updatePullRequestByID().'
            );
        }

        if (requestParameters['updatePullRequestBody'] == null) {
            throw new runtime.RequiredError(
                'updatePullRequestBody',
                'Required parameter "updatePullRequestBody" was null or undefined when calling updatePullRequestByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pullRequestSlug'] != null) {
            queryParameters['pull_request_slug'] = requestParameters['pullRequestSlug'];
        }

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pulls/id:{pull_request_id}`;
        urlPath = urlPath.replace(`{${"pull_request_id"}}`, encodeURIComponent(String(requestParameters['pullRequestId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePullRequestBodyToJSON(requestParameters['updatePullRequestBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PullRequestFromJSON(jsonValue));
    }

    /**
     * Update PullRequest (By ID)
     */
    async updatePullRequestByID(requestParameters: UpdatePullRequestByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PullRequest> {
        const response = await this.updatePullRequestByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
