/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CreateLabelBody,
  ListLabelsForRepositoryResponse,
  UpdateLabelBody,
  V1Label,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CreateLabelBodyFromJSON,
    CreateLabelBodyToJSON,
    ListLabelsForRepositoryResponseFromJSON,
    ListLabelsForRepositoryResponseToJSON,
    UpdateLabelBodyFromJSON,
    UpdateLabelBodyToJSON,
    V1LabelFromJSON,
    V1LabelToJSON,
} from '../models/index';

export interface CreateLabelRequest {
    orgSlug: string;
    repoSlug: string;
    createLabelBody: CreateLabelBody;
    silent?: boolean;
}

export interface CreateLabelByIDRequest {
    repoId: string;
    createLabelBody: CreateLabelBody;
    silent?: boolean;
}

export interface DeleteLabelRequest {
    orgSlug: string;
    repoSlug: string;
    labelSlug: string;
    silent?: boolean;
}

export interface DeleteLabelByIDRequest {
    labelId: string;
    silent?: boolean;
}

export interface GetLabelRequest {
    orgSlug: string;
    repoSlug: string;
    labelSlug: string;
}

export interface GetLabelByIDRequest {
    labelId: string;
}

export interface ListLabelsForRepositoryRequest {
    orgSlug: string;
    repoSlug: string;
    pageSize?: string;
    pageToken?: string;
    sortBy?: string;
    filter?: string;
}

export interface ListLabelsForRepositoryByIDRequest {
    repoId: string;
    pageSize?: string;
    pageToken?: string;
    sortBy?: string;
    filter?: string;
}

export interface UpdateLabelRequest {
    orgSlug: string;
    repoSlug: string;
    labelSlug: string;
    updateLabelBody: UpdateLabelBody;
    silent?: boolean;
}

export interface UpdateLabelByIDRequest {
    labelId: string;
    updateLabelBody: UpdateLabelBody;
    silent?: boolean;
}

/**
 * RepositoryLabelsApi - interface
 * 
 * @export
 * @interface RepositoryLabelsApiInterface
 */
export interface RepositoryLabelsApiInterface {
    /**
     * 
     * @summary Create Label
     * @param {string} orgSlug Path parameters for different routes
     * @param {string} repoSlug 
     * @param {CreateLabelBody} createLabelBody 
     * @param {boolean} [silent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    createLabelRaw(requestParameters: CreateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>>;

    /**
     * Create Label
     */
    createLabel(requestParameters: CreateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label>;

    /**
     * 
     * @summary Create Label (By ID)
     * @param {string} repoId 
     * @param {CreateLabelBody} createLabelBody 
     * @param {boolean} [silent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    createLabelByIDRaw(requestParameters: CreateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>>;

    /**
     * Create Label (By ID)
     */
    createLabelByID(requestParameters: CreateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label>;

    /**
     * 
     * @summary Delete label (By Slug)
     * @param {string} orgSlug Path parameters for different routes
     * @param {string} repoSlug 
     * @param {string} labelSlug 
     * @param {boolean} [silent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    deleteLabelRaw(requestParameters: DeleteLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete label (By Slug)
     */
    deleteLabel(requestParameters: DeleteLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Delete label (By Label ID)
     * @param {string} labelId 
     * @param {boolean} [silent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    deleteLabelByIDRaw(requestParameters: DeleteLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete label (By Label ID)
     */
    deleteLabelByID(requestParameters: DeleteLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get Label (By Slug)
     * @param {string} orgSlug Path parameters for different routes
     * @param {string} repoSlug 
     * @param {string} labelSlug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    getLabelRaw(requestParameters: GetLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>>;

    /**
     * Get Label (By Slug)
     */
    getLabel(requestParameters: GetLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label>;

    /**
     * 
     * @summary Get Label (By Label ID)
     * @param {string} labelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    getLabelByIDRaw(requestParameters: GetLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>>;

    /**
     * Get Label (By Label ID)
     */
    getLabelByID(requestParameters: GetLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label>;

    /**
     * 
     * @summary List labels
     * @param {string} orgSlug Path parameters for different routes
     * @param {string} repoSlug 
     * @param {string} [pageSize] 
     * @param {string} [pageToken] 
     * @param {string} [sortBy] 
     * @param {string} [filter] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    listLabelsForRepositoryRaw(requestParameters: ListLabelsForRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLabelsForRepositoryResponse>>;

    /**
     * List labels
     */
    listLabelsForRepository(requestParameters: ListLabelsForRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLabelsForRepositoryResponse>;

    /**
     * 
     * @summary List labels (By ID)
     * @param {string} repoId 
     * @param {string} [pageSize] 
     * @param {string} [pageToken] 
     * @param {string} [sortBy] 
     * @param {string} [filter] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    listLabelsForRepositoryByIDRaw(requestParameters: ListLabelsForRepositoryByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLabelsForRepositoryResponse>>;

    /**
     * List labels (By ID)
     */
    listLabelsForRepositoryByID(requestParameters: ListLabelsForRepositoryByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLabelsForRepositoryResponse>;

    /**
     * 
     * @summary Update Label (By Slug)
     * @param {string} orgSlug Path parameters for different routes
     * @param {string} repoSlug 
     * @param {string} labelSlug 
     * @param {UpdateLabelBody} updateLabelBody 
     * @param {boolean} [silent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    updateLabelRaw(requestParameters: UpdateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>>;

    /**
     * Update Label (By Slug)
     */
    updateLabel(requestParameters: UpdateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label>;

    /**
     * 
     * @summary Update Label (By Label ID)
     * @param {string} labelId 
     * @param {UpdateLabelBody} updateLabelBody 
     * @param {boolean} [silent] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RepositoryLabelsApiInterface
     */
    updateLabelByIDRaw(requestParameters: UpdateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>>;

    /**
     * Update Label (By Label ID)
     */
    updateLabelByID(requestParameters: UpdateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label>;

}

/**
 * 
 */
export class RepositoryLabelsApi extends runtime.BaseAPI implements RepositoryLabelsApiInterface {

    /**
     * Create Label
     */
    async createLabelRaw(requestParameters: CreateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling createLabel().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling createLabel().'
            );
        }

        if (requestParameters['createLabelBody'] == null) {
            throw new runtime.RequiredError(
                'createLabelBody',
                'Required parameter "createLabelBody" was null or undefined when calling createLabel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/labels`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLabelBodyToJSON(requestParameters['createLabelBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LabelFromJSON(jsonValue));
    }

    /**
     * Create Label
     */
    async createLabel(requestParameters: CreateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label> {
        const response = await this.createLabelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Label (By ID)
     */
    async createLabelByIDRaw(requestParameters: CreateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>> {
        if (requestParameters['repoId'] == null) {
            throw new runtime.RequiredError(
                'repoId',
                'Required parameter "repoId" was null or undefined when calling createLabelByID().'
            );
        }

        if (requestParameters['createLabelBody'] == null) {
            throw new runtime.RequiredError(
                'createLabelBody',
                'Required parameter "createLabelBody" was null or undefined when calling createLabelByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/id:{repo_id}/labels`;
        urlPath = urlPath.replace(`{${"repo_id"}}`, encodeURIComponent(String(requestParameters['repoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLabelBodyToJSON(requestParameters['createLabelBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LabelFromJSON(jsonValue));
    }

    /**
     * Create Label (By ID)
     */
    async createLabelByID(requestParameters: CreateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label> {
        const response = await this.createLabelByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete label (By Slug)
     */
    async deleteLabelRaw(requestParameters: DeleteLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling deleteLabel().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling deleteLabel().'
            );
        }

        if (requestParameters['labelSlug'] == null) {
            throw new runtime.RequiredError(
                'labelSlug',
                'Required parameter "labelSlug" was null or undefined when calling deleteLabel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/labels/{label_slug}`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"label_slug"}}`, encodeURIComponent(String(requestParameters['labelSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete label (By Slug)
     */
    async deleteLabel(requestParameters: DeleteLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLabelRaw(requestParameters, initOverrides);
    }

    /**
     * Delete label (By Label ID)
     */
    async deleteLabelByIDRaw(requestParameters: DeleteLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['labelId'] == null) {
            throw new runtime.RequiredError(
                'labelId',
                'Required parameter "labelId" was null or undefined when calling deleteLabelByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/labels/id:{label_id}`;
        urlPath = urlPath.replace(`{${"label_id"}}`, encodeURIComponent(String(requestParameters['labelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete label (By Label ID)
     */
    async deleteLabelByID(requestParameters: DeleteLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLabelByIDRaw(requestParameters, initOverrides);
    }

    /**
     * Get Label (By Slug)
     */
    async getLabelRaw(requestParameters: GetLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling getLabel().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling getLabel().'
            );
        }

        if (requestParameters['labelSlug'] == null) {
            throw new runtime.RequiredError(
                'labelSlug',
                'Required parameter "labelSlug" was null or undefined when calling getLabel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/labels/{label_slug}`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"label_slug"}}`, encodeURIComponent(String(requestParameters['labelSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LabelFromJSON(jsonValue));
    }

    /**
     * Get Label (By Slug)
     */
    async getLabel(requestParameters: GetLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label> {
        const response = await this.getLabelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Label (By Label ID)
     */
    async getLabelByIDRaw(requestParameters: GetLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>> {
        if (requestParameters['labelId'] == null) {
            throw new runtime.RequiredError(
                'labelId',
                'Required parameter "labelId" was null or undefined when calling getLabelByID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/labels/id:{label_id}`;
        urlPath = urlPath.replace(`{${"label_id"}}`, encodeURIComponent(String(requestParameters['labelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LabelFromJSON(jsonValue));
    }

    /**
     * Get Label (By Label ID)
     */
    async getLabelByID(requestParameters: GetLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label> {
        const response = await this.getLabelByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List labels
     */
    async listLabelsForRepositoryRaw(requestParameters: ListLabelsForRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLabelsForRepositoryResponse>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling listLabelsForRepository().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling listLabelsForRepository().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/labels`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListLabelsForRepositoryResponseFromJSON(jsonValue));
    }

    /**
     * List labels
     */
    async listLabelsForRepository(requestParameters: ListLabelsForRepositoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLabelsForRepositoryResponse> {
        const response = await this.listLabelsForRepositoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List labels (By ID)
     */
    async listLabelsForRepositoryByIDRaw(requestParameters: ListLabelsForRepositoryByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListLabelsForRepositoryResponse>> {
        if (requestParameters['repoId'] == null) {
            throw new runtime.RequiredError(
                'repoId',
                'Required parameter "repoId" was null or undefined when calling listLabelsForRepositoryByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['page_token'] = requestParameters['pageToken'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sort_by'] = requestParameters['sortBy'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/id:{repo_id}/labels`;
        urlPath = urlPath.replace(`{${"repo_id"}}`, encodeURIComponent(String(requestParameters['repoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListLabelsForRepositoryResponseFromJSON(jsonValue));
    }

    /**
     * List labels (By ID)
     */
    async listLabelsForRepositoryByID(requestParameters: ListLabelsForRepositoryByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListLabelsForRepositoryResponse> {
        const response = await this.listLabelsForRepositoryByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Label (By Slug)
     */
    async updateLabelRaw(requestParameters: UpdateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>> {
        if (requestParameters['orgSlug'] == null) {
            throw new runtime.RequiredError(
                'orgSlug',
                'Required parameter "orgSlug" was null or undefined when calling updateLabel().'
            );
        }

        if (requestParameters['repoSlug'] == null) {
            throw new runtime.RequiredError(
                'repoSlug',
                'Required parameter "repoSlug" was null or undefined when calling updateLabel().'
            );
        }

        if (requestParameters['labelSlug'] == null) {
            throw new runtime.RequiredError(
                'labelSlug',
                'Required parameter "labelSlug" was null or undefined when calling updateLabel().'
            );
        }

        if (requestParameters['updateLabelBody'] == null) {
            throw new runtime.RequiredError(
                'updateLabelBody',
                'Required parameter "updateLabelBody" was null or undefined when calling updateLabel().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/repos/{org_slug}/{repo_slug}/labels/{label_slug}`;
        urlPath = urlPath.replace(`{${"org_slug"}}`, encodeURIComponent(String(requestParameters['orgSlug'])));
        urlPath = urlPath.replace(`{${"repo_slug"}}`, encodeURIComponent(String(requestParameters['repoSlug'])));
        urlPath = urlPath.replace(`{${"label_slug"}}`, encodeURIComponent(String(requestParameters['labelSlug'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateLabelBodyToJSON(requestParameters['updateLabelBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LabelFromJSON(jsonValue));
    }

    /**
     * Update Label (By Slug)
     */
    async updateLabel(requestParameters: UpdateLabelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label> {
        const response = await this.updateLabelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Label (By Label ID)
     */
    async updateLabelByIDRaw(requestParameters: UpdateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1Label>> {
        if (requestParameters['labelId'] == null) {
            throw new runtime.RequiredError(
                'labelId',
                'Required parameter "labelId" was null or undefined when calling updateLabelByID().'
            );
        }

        if (requestParameters['updateLabelBody'] == null) {
            throw new runtime.RequiredError(
                'updateLabelBody',
                'Required parameter "updateLabelBody" was null or undefined when calling updateLabelByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['silent'] != null) {
            queryParameters['silent'] = requestParameters['silent'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/labels/id:{label_id}`;
        urlPath = urlPath.replace(`{${"label_id"}}`, encodeURIComponent(String(requestParameters['labelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateLabelBodyToJSON(requestParameters['updateLabelBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1LabelFromJSON(jsonValue));
    }

    /**
     * Update Label (By Label ID)
     */
    async updateLabelByID(requestParameters: UpdateLabelByIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1Label> {
        const response = await this.updateLabelByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
