/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ApiErrorResponse, ListRepositoryPullRequestsResponse } from "../models/index";
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ListRepositoryPullRequestsResponseFromJSON,
    ListRepositoryPullRequestsResponseToJSON,
} from "../models/index";

export interface ListUserPullRequestsRequest {
    userSlug: string;
    userId?: string;
    role?: ListUserPullRequestsRoleEnum;
    pageSize?: string;
    pageToken?: string;
    sortBy?: string;
}

export interface ListUserPullRequestsByIDRequest {
    userId: string;
    userSlug?: string;
    role?: ListUserPullRequestsByIDRoleEnum;
    pageSize?: string;
    pageToken?: string;
    sortBy?: string;
}

/**
 * UserPullRequestApi - interface
 *
 * @export
 * @interface UserPullRequestApiInterface
 */
export interface UserPullRequestApiInterface {
    /**
     * Lists pull requests related to a user identified by user slug.
     * @summary List User Pull Requests
     * @param {string} userSlug
     * @param {string} [userId]
     * @param {'author' | 'reviewer' | 'any'} [role] Role by which PRs should be selected: author, reviewer or any
     * @param {string} [pageSize] The maximum number of pull requests to return. The service may return fewer than this value
     * @param {string} [pageToken] A page token, received from a previous call. Provide this to retrieve the subsequent page.  When paginating, all other parameters must match the call that provided the page token.
     * @param {string} [sortBy] Ordering options: comma separated list of fields. For example: \&quot;name, created_at\&quot; Default sorting order is ascending. To specify descending order for a field, append a \&quot;-\&quot; prefix; for example: \&quot;name, -created_at\&quot; Redundant space characters in the syntax are insignificant. \&quot;foo, -bar\&quot;, \&quot; foo , -bar\&quot;, and \&quot;foo,bar\&quot; are all equivalent. Available fields: title, created_at, updated_at
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPullRequestApiInterface
     */
    listUserPullRequestsRaw(
        requestParameters: ListUserPullRequestsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ListRepositoryPullRequestsResponse>>;

    /**
     * Lists pull requests related to a user identified by user slug.
     * List User Pull Requests
     */
    listUserPullRequests(
        requestParameters: ListUserPullRequestsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ListRepositoryPullRequestsResponse>;

    /**
     * Lists pull requests related to a user identified by UUID.
     * @summary List User Pull Requests (By User ID)
     * @param {string} userId
     * @param {string} [userSlug]
     * @param {'author' | 'reviewer' | 'any'} [role] Role by which PRs should be selected: author, reviewer or any
     * @param {string} [pageSize] The maximum number of pull requests to return. The service may return fewer than this value
     * @param {string} [pageToken] A page token, received from a previous call. Provide this to retrieve the subsequent page.  When paginating, all other parameters must match the call that provided the page token.
     * @param {string} [sortBy] Ordering options: comma separated list of fields. For example: \&quot;name, created_at\&quot; Default sorting order is ascending. To specify descending order for a field, append a \&quot;-\&quot; prefix; for example: \&quot;name, -created_at\&quot; Redundant space characters in the syntax are insignificant. \&quot;foo, -bar\&quot;, \&quot; foo , -bar\&quot;, and \&quot;foo,bar\&quot; are all equivalent. Available fields: title, created_at, updated_at
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPullRequestApiInterface
     */
    listUserPullRequestsByIDRaw(
        requestParameters: ListUserPullRequestsByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ListRepositoryPullRequestsResponse>>;

    /**
     * Lists pull requests related to a user identified by UUID.
     * List User Pull Requests (By User ID)
     */
    listUserPullRequestsByID(
        requestParameters: ListUserPullRequestsByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ListRepositoryPullRequestsResponse>;
}

/**
 *
 */
export class UserPullRequestApi extends runtime.BaseAPI implements UserPullRequestApiInterface {
    /**
     * Lists pull requests related to a user identified by user slug.
     * List User Pull Requests
     */
    async listUserPullRequestsRaw(
        requestParameters: ListUserPullRequestsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ListRepositoryPullRequestsResponse>> {
        if (requestParameters["userSlug"] == null) {
            throw new runtime.RequiredError(
                "userSlug",
                'Required parameter "userSlug" was null or undefined when calling listUserPullRequests().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters["userId"] != null) {
            queryParameters["user_id"] = requestParameters["userId"];
        }

        if (requestParameters["role"] != null) {
            queryParameters["role"] = requestParameters["role"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        if (requestParameters["pageToken"] != null) {
            queryParameters["page_token"] = requestParameters["pageToken"];
        }

        if (requestParameters["sortBy"] != null) {
            queryParameters["sort_by"] = requestParameters["sortBy"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/{user_slug}/pulls`;
        urlPath = urlPath.replace(
            `{${"user_slug"}}`,
            encodeURIComponent(String(requestParameters["userSlug"]))
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ListRepositoryPullRequestsResponseFromJSON(jsonValue)
        );
    }

    /**
     * Lists pull requests related to a user identified by user slug.
     * List User Pull Requests
     */
    async listUserPullRequests(
        requestParameters: ListUserPullRequestsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ListRepositoryPullRequestsResponse> {
        const response = await this.listUserPullRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lists pull requests related to a user identified by UUID.
     * List User Pull Requests (By User ID)
     */
    async listUserPullRequestsByIDRaw(
        requestParameters: ListUserPullRequestsByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ListRepositoryPullRequestsResponse>> {
        if (requestParameters["userId"] == null) {
            throw new runtime.RequiredError(
                "userId",
                'Required parameter "userId" was null or undefined when calling listUserPullRequestsByID().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters["userSlug"] != null) {
            queryParameters["user_slug"] = requestParameters["userSlug"];
        }

        if (requestParameters["role"] != null) {
            queryParameters["role"] = requestParameters["role"];
        }

        if (requestParameters["pageSize"] != null) {
            queryParameters["page_size"] = requestParameters["pageSize"];
        }

        if (requestParameters["pageToken"] != null) {
            queryParameters["page_token"] = requestParameters["pageToken"];
        }

        if (requestParameters["sortBy"] != null) {
            queryParameters["sort_by"] = requestParameters["sortBy"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/users/id:{user_id}/pulls`;
        urlPath = urlPath.replace(
            `{${"user_id"}}`,
            encodeURIComponent(String(requestParameters["userId"]))
        );

        const response = await this.request(
            {
                path: urlPath,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            ListRepositoryPullRequestsResponseFromJSON(jsonValue)
        );
    }

    /**
     * Lists pull requests related to a user identified by UUID.
     * List User Pull Requests (By User ID)
     */
    async listUserPullRequestsByID(
        requestParameters: ListUserPullRequestsByIDRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<ListRepositoryPullRequestsResponse> {
        const response = await this.listUserPullRequestsByIDRaw(requestParameters, initOverrides);
        return await response.value();
    }
}

/**
 * @export
 */
export const ListUserPullRequestsRoleEnum = {
    Author: "author",
    Reviewer: "reviewer",
    Any: "any",
} as const;
export type ListUserPullRequestsRoleEnum =
    (typeof ListUserPullRequestsRoleEnum)[keyof typeof ListUserPullRequestsRoleEnum];
/**
 * @export
 */
export const ListUserPullRequestsByIDRoleEnum = {
    Author: "author",
    Reviewer: "reviewer",
    Any: "any",
} as const;
export type ListUserPullRequestsByIDRoleEnum =
    (typeof ListUserPullRequestsByIDRoleEnum)[keyof typeof ListUserPullRequestsByIDRoleEnum];
