/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof ApiErrorResponse
     */
    details?: { [key: string]: string };
    /**
     *
     * @type {string}
     * @memberof ApiErrorResponse
     */
    errorCode?: string;
    /**
     *
     * @type {string}
     * @memberof ApiErrorResponse
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof ApiErrorResponse
     */
    requestId?: string;
}

/**
 * Check if a given object implements the ApiErrorResponse interface.
 */
export function instanceOfApiErrorResponse(value: object): value is ApiErrorResponse {
    return true;
}

export function ApiErrorResponseFromJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseFromJSONTyped(json, false);
}

export function ApiErrorResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ApiErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        details: json["details"] == null ? undefined : json["details"],
        errorCode: json["error_code"] == null ? undefined : json["error_code"],
        message: json["message"] == null ? undefined : json["message"],
        requestId: json["request_id"] == null ? undefined : json["request_id"],
    };
}

export function ApiErrorResponseToJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseToJSONTyped(json, false);
}

export function ApiErrorResponseToJSONTyped(
    value?: ApiErrorResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        details: value["details"],
        error_code: value["errorCode"],
        message: value["message"],
        request_id: value["requestId"],
    };
}
