/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Attachment } from "./Attachment";
import {
    AttachmentFromJSON,
    AttachmentFromJSONTyped,
    AttachmentToJSON,
    AttachmentToJSONTyped,
} from "./Attachment";

/**
 *
 * @export
 * @interface AttachmentsResponse
 */
export interface AttachmentsResponse {
    /**
     *
     * @type {Array<Attachment>}
     * @memberof AttachmentsResponse
     */
    attachments?: Array<Attachment>;
}

/**
 * Check if a given object implements the AttachmentsResponse interface.
 */
export function instanceOfAttachmentsResponse(value: object): value is AttachmentsResponse {
    return true;
}

export function AttachmentsResponseFromJSON(json: any): AttachmentsResponse {
    return AttachmentsResponseFromJSONTyped(json, false);
}

export function AttachmentsResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): AttachmentsResponse {
    if (json == null) {
        return json;
    }
    return {
        attachments:
            json["attachments"] == null
                ? undefined
                : (json["attachments"] as Array<any>).map(AttachmentFromJSON),
    };
}

export function AttachmentsResponseToJSON(json: any): AttachmentsResponse {
    return AttachmentsResponseToJSONTyped(json, false);
}

export function AttachmentsResponseToJSONTyped(
    value?: AttachmentsResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        attachments:
            value["attachments"] == null
                ? undefined
                : (value["attachments"] as Array<any>).map(AttachmentToJSON),
    };
}
