/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentEmbedded
 */
export interface AttachmentEmbedded {
    /**
     * 
     * @type {string}
     * @memberof AttachmentEmbedded
     */
    id?: string;
}

/**
 * Check if a given object implements the AttachmentEmbedded interface.
 */
export function instanceOfAttachmentEmbedded(value: object): value is AttachmentEmbedded {
    return true;
}

export function AttachmentEmbeddedFromJSON(json: any): AttachmentEmbedded {
    return AttachmentEmbeddedFromJSONTyped(json, false);
}

export function AttachmentEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AttachmentEmbeddedToJSON(json: any): AttachmentEmbedded {
    return AttachmentEmbeddedToJSONTyped(json, false);
}

export function AttachmentEmbeddedToJSONTyped(value?: AttachmentEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

