/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Commit } from './Commit';
import {
    CommitFromJSON,
    CommitFromJSONTyped,
    CommitToJSON,
    CommitToJSONTyped,
} from './Commit';

/**
 * 
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 
     * @type {Commit}
     * @memberof Branch
     */
    commit?: Commit;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    name?: string;
}

/**
 * Check if a given object implements the Branch interface.
 */
export function instanceOfBranch(value: object): value is Branch {
    return true;
}

export function BranchFromJSON(json: any): Branch {
    return BranchFromJSONTyped(json, false);
}

export function BranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Branch {
    if (json == null) {
        return json;
    }
    return {
        
        'commit': json['commit'] == null ? undefined : CommitFromJSON(json['commit']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BranchToJSON(json: any): Branch {
    return BranchToJSONTyped(json, false);
}

export function BranchToJSONTyped(value?: Branch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commit': CommitToJSON(value['commit']),
        'name': value['name'],
    };
}

