/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CloneURL
 */
export interface CloneURL {
    /**
     *
     * @type {string}
     * @memberof CloneURL
     */
    https?: string;
    /**
     *
     * @type {string}
     * @memberof CloneURL
     */
    ssh?: string;
}

/**
 * Check if a given object implements the CloneURL interface.
 */
export function instanceOfCloneURL(value: object): value is CloneURL {
    return true;
}

export function CloneURLFromJSON(json: any): CloneURL {
    return CloneURLFromJSONTyped(json, false);
}

export function CloneURLFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloneURL {
    if (json == null) {
        return json;
    }
    return {
        https: json["https"] == null ? undefined : json["https"],
        ssh: json["ssh"] == null ? undefined : json["ssh"],
    };
}

export function CloneURLToJSON(json: any): CloneURL {
    return CloneURLToJSONTyped(json, false);
}

export function CloneURLToJSONTyped(
    value?: CloneURL | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        https: value["https"],
        ssh: value["ssh"],
    };
}
