/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CommitFileChanges
 */
export interface CommitFileChanges {
    /**
     * Files that were added in this commit.
     * Limited to 1000 files maximum. Empty list means no files were added.
     * @type {Array<string>}
     * @memberof CommitFileChanges
     */
    added?: Array<string>;
    /**
     * Files that were modified in this commit.
     * Limited to 1000 files maximum. Empty list means no files were modified.
     * @type {Array<string>}
     * @memberof CommitFileChanges
     */
    modified?: Array<string>;
    /**
     * Files that were removed in this commit.
     * Limited to 1000 files maximum. Empty list means no files were removed.
     * @type {Array<string>}
     * @memberof CommitFileChanges
     */
    removed?: Array<string>;
}

/**
 * Check if a given object implements the CommitFileChanges interface.
 */
export function instanceOfCommitFileChanges(value: object): value is CommitFileChanges {
    return true;
}

export function CommitFileChangesFromJSON(json: any): CommitFileChanges {
    return CommitFileChangesFromJSONTyped(json, false);
}

export function CommitFileChangesFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CommitFileChanges {
    if (json == null) {
        return json;
    }
    return {
        added: json["added"] == null ? undefined : json["added"],
        modified: json["modified"] == null ? undefined : json["modified"],
        removed: json["removed"] == null ? undefined : json["removed"],
    };
}

export function CommitFileChangesToJSON(json: any): CommitFileChanges {
    return CommitFileChangesToJSONTyped(json, false);
}

export function CommitFileChangesToJSONTyped(
    value?: CommitFileChanges | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        added: value["added"],
        modified: value["modified"],
        removed: value["removed"],
    };
}
