/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { InviteeInput } from "./InviteeInput";
import {
    InviteeInputFromJSON,
    InviteeInputFromJSONTyped,
    InviteeInputToJSON,
    InviteeInputToJSONTyped,
} from "./InviteeInput";

/**
 *
 * @export
 * @interface CreateOrganizationInvitesBody
 */
export interface CreateOrganizationInvitesBody {
    /**
     *
     * @type {Array<InviteeInput>}
     * @memberof CreateOrganizationInvitesBody
     */
    invitees?: Array<InviteeInput>;
    /**
     *
     * @type {number}
     * @memberof CreateOrganizationInvitesBody
     */
    ttlInDays?: number;
}

/**
 * Check if a given object implements the CreateOrganizationInvitesBody interface.
 */
export function instanceOfCreateOrganizationInvitesBody(
    value: object
): value is CreateOrganizationInvitesBody {
    return true;
}

export function CreateOrganizationInvitesBodyFromJSON(json: any): CreateOrganizationInvitesBody {
    return CreateOrganizationInvitesBodyFromJSONTyped(json, false);
}

export function CreateOrganizationInvitesBodyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateOrganizationInvitesBody {
    if (json == null) {
        return json;
    }
    return {
        invitees:
            json["invitees"] == null
                ? undefined
                : (json["invitees"] as Array<any>).map(InviteeInputFromJSON),
        ttlInDays: json["ttl_in_days"] == null ? undefined : json["ttl_in_days"],
    };
}

export function CreateOrganizationInvitesBodyToJSON(json: any): CreateOrganizationInvitesBody {
    return CreateOrganizationInvitesBodyToJSONTyped(json, false);
}

export function CreateOrganizationInvitesBodyToJSONTyped(
    value?: CreateOrganizationInvitesBody | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        invitees:
            value["invitees"] == null
                ? undefined
                : (value["invitees"] as Array<any>).map(InviteeInputToJSON),
        ttl_in_days: value["ttlInDays"],
    };
}
