/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateReleaseBody
 */
export interface CreateReleaseBody {
    /**
     *
     * @type {boolean}
     * @memberof CreateReleaseBody
     */
    publish?: boolean;
    /**
     *
     * @type {string}
     * @memberof CreateReleaseBody
     */
    releaseNotes?: string;
    /**
     *
     * @type {string}
     * @memberof CreateReleaseBody
     */
    tag?: string;
    /**
     *
     * @type {string}
     * @memberof CreateReleaseBody
     */
    targetBranch?: string;
    /**
     *
     * @type {string}
     * @memberof CreateReleaseBody
     */
    title?: string;
}

/**
 * Check if a given object implements the CreateReleaseBody interface.
 */
export function instanceOfCreateReleaseBody(value: object): value is CreateReleaseBody {
    return true;
}

export function CreateReleaseBodyFromJSON(json: any): CreateReleaseBody {
    return CreateReleaseBodyFromJSONTyped(json, false);
}

export function CreateReleaseBodyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateReleaseBody {
    if (json == null) {
        return json;
    }
    return {
        publish: json["publish"] == null ? undefined : json["publish"],
        releaseNotes: json["release_notes"] == null ? undefined : json["release_notes"],
        tag: json["tag"] == null ? undefined : json["tag"],
        targetBranch: json["target_branch"] == null ? undefined : json["target_branch"],
        title: json["title"] == null ? undefined : json["title"],
    };
}

export function CreateReleaseBodyToJSON(json: any): CreateReleaseBody {
    return CreateReleaseBodyToJSONTyped(json, false);
}

export function CreateReleaseBodyToJSONTyped(
    value?: CreateReleaseBody | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        publish: value["publish"],
        release_notes: value["releaseNotes"],
        tag: value["tag"],
        target_branch: value["targetBranch"],
        title: value["title"],
    };
}
