/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { InviteError } from "./InviteError";
import {
    InviteErrorFromJSON,
    InviteErrorFromJSONTyped,
    InviteErrorToJSON,
    InviteErrorToJSONTyped,
} from "./InviteError";
import type { Invite } from "./Invite";
import { InviteFromJSON, InviteFromJSONTyped, InviteToJSON, InviteToJSONTyped } from "./Invite";

/**
 *
 * @export
 * @interface CreateOrganizationInvitesOperationResult
 */
export interface CreateOrganizationInvitesOperationResult {
    /**
     * Per-invite errors. Each error identifies which invitee failed and why.
     * @type {Array<InviteError>}
     * @memberof CreateOrganizationInvitesOperationResult
     */
    errors?: Array<InviteError>;
    /**
     * Invites that were successfully created and are waiting for acceptance.
     * @type {Array<Invite>}
     * @memberof CreateOrganizationInvitesOperationResult
     */
    invites?: Array<Invite>;
}

/**
 * Check if a given object implements the CreateOrganizationInvitesOperationResult interface.
 */
export function instanceOfCreateOrganizationInvitesOperationResult(
    value: object
): value is CreateOrganizationInvitesOperationResult {
    return true;
}

export function CreateOrganizationInvitesOperationResultFromJSON(
    json: any
): CreateOrganizationInvitesOperationResult {
    return CreateOrganizationInvitesOperationResultFromJSONTyped(json, false);
}

export function CreateOrganizationInvitesOperationResultFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateOrganizationInvitesOperationResult {
    if (json == null) {
        return json;
    }
    return {
        errors:
            json["errors"] == null
                ? undefined
                : (json["errors"] as Array<any>).map(InviteErrorFromJSON),
        invites:
            json["invites"] == null
                ? undefined
                : (json["invites"] as Array<any>).map(InviteFromJSON),
    };
}

export function CreateOrganizationInvitesOperationResultToJSON(
    json: any
): CreateOrganizationInvitesOperationResult {
    return CreateOrganizationInvitesOperationResultToJSONTyped(json, false);
}

export function CreateOrganizationInvitesOperationResultToJSONTyped(
    value?: CreateOrganizationInvitesOperationResult | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        errors:
            value["errors"] == null
                ? undefined
                : (value["errors"] as Array<any>).map(InviteErrorToJSON),
        invites:
            value["invites"] == null
                ? undefined
                : (value["invites"] as Array<any>).map(InviteToJSON),
    };
}
