/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { OperationStatus } from "./OperationStatus";
import {
    OperationStatusFromJSON,
    OperationStatusFromJSONTyped,
    OperationStatusToJSON,
    OperationStatusToJSONTyped,
} from "./OperationStatus";
import type { CreateOrganizationInvitesOperationResult } from "./CreateOrganizationInvitesOperationResult";
import {
    CreateOrganizationInvitesOperationResultFromJSON,
    CreateOrganizationInvitesOperationResultFromJSONTyped,
    CreateOrganizationInvitesOperationResultToJSON,
    CreateOrganizationInvitesOperationResultToJSONTyped,
} from "./CreateOrganizationInvitesOperationResult";
import type { OperationError } from "./OperationError";
import {
    OperationErrorFromJSON,
    OperationErrorFromJSONTyped,
    OperationErrorToJSON,
    OperationErrorToJSONTyped,
} from "./OperationError";

/**
 *
 * @export
 * @interface CreateOrganizationInvitesOperation
 */
export interface CreateOrganizationInvitesOperation {
    /**
     *
     * @type {Date}
     * @memberof CreateOrganizationInvitesOperation
     */
    createdAt?: Date;
    /**
     *
     * @type {OperationError}
     * @memberof CreateOrganizationInvitesOperation
     */
    error?: OperationError;
    /**
     *
     * @type {Date}
     * @memberof CreateOrganizationInvitesOperation
     */
    modifiedAt?: Date;
    /**
     *
     * @type {string}
     * @memberof CreateOrganizationInvitesOperation
     */
    operationId?: string;
    /**
     *
     * @type {CreateOrganizationInvitesOperationResult}
     * @memberof CreateOrganizationInvitesOperation
     */
    response?: CreateOrganizationInvitesOperationResult;
    /**
     *
     * @type {OperationStatus}
     * @memberof CreateOrganizationInvitesOperation
     */
    status?: OperationStatus;
    /**
     *
     * @type {string}
     * @memberof CreateOrganizationInvitesOperation
     */
    statusUrl?: string;
}

/**
 * Check if a given object implements the CreateOrganizationInvitesOperation interface.
 */
export function instanceOfCreateOrganizationInvitesOperation(
    value: object
): value is CreateOrganizationInvitesOperation {
    return true;
}

export function CreateOrganizationInvitesOperationFromJSON(
    json: any
): CreateOrganizationInvitesOperation {
    return CreateOrganizationInvitesOperationFromJSONTyped(json, false);
}

export function CreateOrganizationInvitesOperationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CreateOrganizationInvitesOperation {
    if (json == null) {
        return json;
    }
    return {
        createdAt: json["created_at"] == null ? undefined : new Date(json["created_at"]),
        error: json["error"] == null ? undefined : OperationErrorFromJSON(json["error"]),
        modifiedAt: json["modified_at"] == null ? undefined : new Date(json["modified_at"]),
        operationId: json["operation_id"] == null ? undefined : json["operation_id"],
        response:
            json["response"] == null
                ? undefined
                : CreateOrganizationInvitesOperationResultFromJSON(json["response"]),
        status: json["status"] == null ? undefined : OperationStatusFromJSON(json["status"]),
        statusUrl: json["status_url"] == null ? undefined : json["status_url"],
    };
}

export function CreateOrganizationInvitesOperationToJSON(
    json: any
): CreateOrganizationInvitesOperation {
    return CreateOrganizationInvitesOperationToJSONTyped(json, false);
}

export function CreateOrganizationInvitesOperationToJSONTyped(
    value?: CreateOrganizationInvitesOperation | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        created_at:
            value["createdAt"] == null ? value["createdAt"] : value["createdAt"].toISOString(),
        error: OperationErrorToJSON(value["error"]),
        modified_at:
            value["modifiedAt"] == null ? value["modifiedAt"] : value["modifiedAt"].toISOString(),
        operation_id: value["operationId"],
        response: CreateOrganizationInvitesOperationResultToJSON(value["response"]),
        status: OperationStatusToJSON(value["status"]),
        status_url: value["statusUrl"],
    };
}
