/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { UserEmbedded } from "./UserEmbedded";
import {
    UserEmbeddedFromJSON,
    UserEmbeddedFromJSONTyped,
    UserEmbeddedToJSON,
    UserEmbeddedToJSONTyped,
} from "./UserEmbedded";

/**
 *
 * @export
 * @interface EventHeader
 */
export interface EventHeader {
    /**
     *
     * @type {string}
     * @memberof EventHeader
     */
    aggregateId?: string;
    /**
     *
     * @type {string}
     * @memberof EventHeader
     */
    aggregateType?: string;
    /**
     * Causation ID is the ID of the event that directly caused this event.
     * Empty for root events (events triggered directly by user actions).
     * Used to reconstruct the event tree within a correlation chain.
     * @type {string}
     * @memberof EventHeader
     */
    causationId?: string;
    /**
     * Correlation ID for tracking event chains back to the original request.
     * Uses request_id from the originating gRPC/HTTP request when available,
     * falls back to trace_id or the root event's ID.
     * @type {string}
     * @memberof EventHeader
     */
    correlationId?: string;
    /**
     *
     * @type {string}
     * @memberof EventHeader
     */
    id?: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof EventHeader
     */
    metadata?: { [key: string]: string };
    /**
     *
     * @type {Date}
     * @memberof EventHeader
     */
    occurredAt?: Date;
    /**
     *
     * @type {string}
     * @memberof EventHeader
     */
    organizationId?: string;
    /**
     *
     * @type {string}
     * @memberof EventHeader
     */
    repositoryId?: string;
    /**
     *
     * @type {UserEmbedded}
     * @memberof EventHeader
     */
    triggeredBy?: UserEmbedded;
    /**
     *
     * @type {string}
     * @memberof EventHeader
     */
    type?: string;
}

/**
 * Check if a given object implements the EventHeader interface.
 */
export function instanceOfEventHeader(value: object): value is EventHeader {
    return true;
}

export function EventHeaderFromJSON(json: any): EventHeader {
    return EventHeaderFromJSONTyped(json, false);
}

export function EventHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventHeader {
    if (json == null) {
        return json;
    }
    return {
        aggregateId: json["aggregate_id"] == null ? undefined : json["aggregate_id"],
        aggregateType: json["aggregate_type"] == null ? undefined : json["aggregate_type"],
        causationId: json["causation_id"] == null ? undefined : json["causation_id"],
        correlationId: json["correlation_id"] == null ? undefined : json["correlation_id"],
        id: json["id"] == null ? undefined : json["id"],
        metadata: json["metadata"] == null ? undefined : json["metadata"],
        occurredAt: json["occurred_at"] == null ? undefined : new Date(json["occurred_at"]),
        organizationId: json["organization_id"] == null ? undefined : json["organization_id"],
        repositoryId: json["repository_id"] == null ? undefined : json["repository_id"],
        triggeredBy:
            json["triggered_by"] == null ? undefined : UserEmbeddedFromJSON(json["triggered_by"]),
        type: json["type"] == null ? undefined : json["type"],
    };
}

export function EventHeaderToJSON(json: any): EventHeader {
    return EventHeaderToJSONTyped(json, false);
}

export function EventHeaderToJSONTyped(
    value?: EventHeader | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        aggregate_id: value["aggregateId"],
        aggregate_type: value["aggregateType"],
        causation_id: value["causationId"],
        correlation_id: value["correlationId"],
        id: value["id"],
        metadata: value["metadata"],
        occurred_at:
            value["occurredAt"] == null ? value["occurredAt"] : value["occurredAt"].toISOString(),
        organization_id: value["organizationId"],
        repository_id: value["repositoryId"],
        triggered_by: UserEmbeddedToJSON(value["triggeredBy"]),
        type: value["type"],
    };
}
