/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileType = {
    Image: 'image',
    Document: 'document',
    Video: 'video',
    Container: 'container'
} as const;
export type FileType = typeof FileType[keyof typeof FileType];


export function instanceOfFileType(value: any): boolean {
    for (const key in FileType) {
        if (Object.prototype.hasOwnProperty.call(FileType, key)) {
            if (FileType[key as keyof typeof FileType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileTypeFromJSON(json: any): FileType {
    return FileTypeFromJSONTyped(json, false);
}

export function FileTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileType {
    return json as FileType;
}

export function FileTypeToJSON(value?: FileType | null): any {
    return value as any;
}

export function FileTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FileType {
    return value as FileType;
}

