/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetCubeLogsResponse
 */
export interface GetCubeLogsResponse {
    /**
     * This flag is set to true when the the cube's execution has finished and no more logs will be written.
     * @type {boolean}
     * @memberof GetCubeLogsResponse
     */
    done?: boolean;
    /**
     *
     * @type {string}
     * @memberof GetCubeLogsResponse
     */
    logs?: string;
    /**
     * This flag is set to true when the corresponding page of logs was fully written.
     * If `page_complete` is false, requests for the next pages will result in a status code 'Not Found'.
     * @type {boolean}
     * @memberof GetCubeLogsResponse
     */
    pageComplete?: boolean;
}

/**
 * Check if a given object implements the GetCubeLogsResponse interface.
 */
export function instanceOfGetCubeLogsResponse(value: object): value is GetCubeLogsResponse {
    return true;
}

export function GetCubeLogsResponseFromJSON(json: any): GetCubeLogsResponse {
    return GetCubeLogsResponseFromJSONTyped(json, false);
}

export function GetCubeLogsResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): GetCubeLogsResponse {
    if (json == null) {
        return json;
    }
    return {
        done: json["done"] == null ? undefined : json["done"],
        logs: json["logs"] == null ? undefined : json["logs"],
        pageComplete: json["page_complete"] == null ? undefined : json["page_complete"],
    };
}

export function GetCubeLogsResponseToJSON(json: any): GetCubeLogsResponse {
    return GetCubeLogsResponseToJSONTyped(json, false);
}

export function GetCubeLogsResponseToJSONTyped(
    value?: GetCubeLogsResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        done: value["done"],
        logs: value["logs"],
        page_complete: value["pageComplete"],
    };
}
