/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Exactly one of the fields must be provided
 * @export
 * @interface GitRevision
 */
export interface GitRevision {
    /**
     *
     * @type {string}
     * @memberof GitRevision
     */
    branch?: string;
    /**
     *
     * @type {string}
     * @memberof GitRevision
     */
    commit?: string;
    /**
     *
     * @type {string}
     * @memberof GitRevision
     */
    tag?: string;
}

/**
 * Check if a given object implements the GitRevision interface.
 */
export function instanceOfGitRevision(value: object): value is GitRevision {
    return true;
}

export function GitRevisionFromJSON(json: any): GitRevision {
    return GitRevisionFromJSONTyped(json, false);
}

export function GitRevisionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitRevision {
    if (json == null) {
        return json;
    }
    return {
        branch: json["branch"] == null ? undefined : json["branch"],
        commit: json["commit"] == null ? undefined : json["commit"],
        tag: json["tag"] == null ? undefined : json["tag"],
    };
}

export function GitRevisionToJSON(json: any): GitRevision {
    return GitRevisionToJSONTyped(json, false);
}

export function GitRevisionToJSONTyped(
    value?: GitRevision | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        branch: value["branch"],
        commit: value["commit"],
        tag: value["tag"],
    };
}
