/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface InitSettings
 */
export interface InitSettings {
    /**
     *
     * @type {boolean}
     * @memberof InitSettings
     */
    createReadme?: boolean;
    /**
     *
     * @type {string}
     * @memberof InitSettings
     */
    defaultBranch?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof InitSettings
     */
    gitignorePresets?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof InitSettings
     */
    licenseSlug?: string;
    /**
     *
     * @type {string}
     * @memberof InitSettings
     */
    srcYamlTemplateSlug?: string;
}

/**
 * Check if a given object implements the InitSettings interface.
 */
export function instanceOfInitSettings(value: object): value is InitSettings {
    return true;
}

export function InitSettingsFromJSON(json: any): InitSettings {
    return InitSettingsFromJSONTyped(json, false);
}

export function InitSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InitSettings {
    if (json == null) {
        return json;
    }
    return {
        createReadme: json["create_readme"] == null ? undefined : json["create_readme"],
        defaultBranch: json["default_branch"] == null ? undefined : json["default_branch"],
        gitignorePresets: json["gitignore_presets"] == null ? undefined : json["gitignore_presets"],
        licenseSlug: json["license_slug"] == null ? undefined : json["license_slug"],
        srcYamlTemplateSlug:
            json["src_yaml_template_slug"] == null ? undefined : json["src_yaml_template_slug"],
    };
}

export function InitSettingsToJSON(json: any): InitSettings {
    return InitSettingsToJSONTyped(json, false);
}

export function InitSettingsToJSONTyped(
    value?: InitSettings | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        create_readme: value["createReadme"],
        default_branch: value["defaultBranch"],
        gitignore_presets: value["gitignorePresets"],
        license_slug: value["licenseSlug"],
        src_yaml_template_slug: value["srcYamlTemplateSlug"],
    };
}
