/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const InviteStatus = {
    Creating: "creating",
    Pending: "pending",
    Accepted: "accepted",
    Rejected: "rejected",
} as const;
export type InviteStatus = (typeof InviteStatus)[keyof typeof InviteStatus];

export function instanceOfInviteStatus(value: any): boolean {
    for (const key in InviteStatus) {
        if (Object.prototype.hasOwnProperty.call(InviteStatus, key)) {
            if (InviteStatus[key as keyof typeof InviteStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InviteStatusFromJSON(json: any): InviteStatus {
    return InviteStatusFromJSONTyped(json, false);
}

export function InviteStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteStatus {
    return json as InviteStatus;
}

export function InviteStatusToJSON(value?: InviteStatus | null): any {
    return value as any;
}

export function InviteStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): InviteStatus {
    return value as InviteStatus;
}
