/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const IssueVisibility = {
    Public: "public",
    Private: "private",
} as const;
export type IssueVisibility = (typeof IssueVisibility)[keyof typeof IssueVisibility];

export function instanceOfIssueVisibility(value: any): boolean {
    for (const key in IssueVisibility) {
        if (Object.prototype.hasOwnProperty.call(IssueVisibility, key)) {
            if (IssueVisibility[key as keyof typeof IssueVisibility] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IssueVisibilityFromJSON(json: any): IssueVisibility {
    return IssueVisibilityFromJSONTyped(json, false);
}

export function IssueVisibilityFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): IssueVisibility {
    return json as IssueVisibility;
}

export function IssueVisibilityToJSON(value?: IssueVisibility | null): any {
    return value as any;
}

export function IssueVisibilityToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean
): IssueVisibility {
    return value as IssueVisibility;
}
