/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IssueCommentEmbedded
 */
export interface IssueCommentEmbedded {
    /**
     * 
     * @type {string}
     * @memberof IssueCommentEmbedded
     */
    id?: string;
}

/**
 * Check if a given object implements the IssueCommentEmbedded interface.
 */
export function instanceOfIssueCommentEmbedded(value: object): value is IssueCommentEmbedded {
    return true;
}

export function IssueCommentEmbeddedFromJSON(json: any): IssueCommentEmbedded {
    return IssueCommentEmbeddedFromJSONTyped(json, false);
}

export function IssueCommentEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssueCommentEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function IssueCommentEmbeddedToJSON(json: any): IssueCommentEmbedded {
    return IssueCommentEmbeddedToJSONTyped(json, false);
}

export function IssueCommentEmbeddedToJSONTyped(value?: IssueCommentEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

