/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelEmbedded
 */
export interface LabelEmbedded {
    /**
     * 
     * @type {string}
     * @memberof LabelEmbedded
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof LabelEmbedded
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LabelEmbedded
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LabelEmbedded
     */
    slug?: string;
}

/**
 * Check if a given object implements the LabelEmbedded interface.
 */
export function instanceOfLabelEmbedded(value: object): value is LabelEmbedded {
    return true;
}

export function LabelEmbeddedFromJSON(json: any): LabelEmbedded {
    return LabelEmbeddedFromJSONTyped(json, false);
}

export function LabelEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function LabelEmbeddedToJSON(json: any): LabelEmbedded {
    return LabelEmbeddedToJSONTyped(json, false);
}

export function LabelEmbeddedToJSONTyped(value?: LabelEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

