/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TreeEntry } from "./TreeEntry";
import {
    TreeEntryFromJSON,
    TreeEntryFromJSONTyped,
    TreeEntryToJSON,
    TreeEntryToJSONTyped,
} from "./TreeEntry";

/**
 *
 * @export
 * @interface ListTreeResponse
 */
export interface ListTreeResponse {
    /**
     * A token, which can be sent as `page_token` to retrieve the next page.
     * If this field is omitted, there are no subsequent pages.
     * @type {string}
     * @memberof ListTreeResponse
     */
    nextPageToken?: string;
    /**
     *
     * @type {Array<TreeEntry>}
     * @memberof ListTreeResponse
     */
    trees?: Array<TreeEntry>;
}

/**
 * Check if a given object implements the ListTreeResponse interface.
 */
export function instanceOfListTreeResponse(value: object): value is ListTreeResponse {
    return true;
}

export function ListTreeResponseFromJSON(json: any): ListTreeResponse {
    return ListTreeResponseFromJSONTyped(json, false);
}

export function ListTreeResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ListTreeResponse {
    if (json == null) {
        return json;
    }
    return {
        nextPageToken: json["next_page_token"] == null ? undefined : json["next_page_token"],
        trees:
            json["trees"] == null
                ? undefined
                : (json["trees"] as Array<any>).map(TreeEntryFromJSON),
    };
}

export function ListTreeResponseToJSON(json: any): ListTreeResponse {
    return ListTreeResponseToJSONTyped(json, false);
}

export function ListTreeResponseToJSONTyped(
    value?: ListTreeResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        next_page_token: value["nextPageToken"],
        trees:
            value["trees"] == null
                ? undefined
                : (value["trees"] as Array<any>).map(TreeEntryToJSON),
    };
}
