/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Branch } from "./Branch";
import { BranchFromJSON, BranchFromJSONTyped, BranchToJSON, BranchToJSONTyped } from "./Branch";

/**
 *
 * @export
 * @interface ListBranchesResponse
 */
export interface ListBranchesResponse {
    /**
     *
     * @type {Array<Branch>}
     * @memberof ListBranchesResponse
     */
    branches?: Array<Branch>;
    /**
     * A token, which can be sent as `page_token` to retrieve the next page.
     * If this field is omitted, there are no subsequent pages.
     * @type {string}
     * @memberof ListBranchesResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the ListBranchesResponse interface.
 */
export function instanceOfListBranchesResponse(value: object): value is ListBranchesResponse {
    return true;
}

export function ListBranchesResponseFromJSON(json: any): ListBranchesResponse {
    return ListBranchesResponseFromJSONTyped(json, false);
}

export function ListBranchesResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ListBranchesResponse {
    if (json == null) {
        return json;
    }
    return {
        branches:
            json["branches"] == null
                ? undefined
                : (json["branches"] as Array<any>).map(BranchFromJSON),
        nextPageToken: json["next_page_token"] == null ? undefined : json["next_page_token"],
    };
}

export function ListBranchesResponseToJSON(json: any): ListBranchesResponse {
    return ListBranchesResponseToJSONTyped(json, false);
}

export function ListBranchesResponseToJSONTyped(
    value?: ListBranchesResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        branches:
            value["branches"] == null
                ? undefined
                : (value["branches"] as Array<any>).map(BranchToJSON),
        next_page_token: value["nextPageToken"],
    };
}
