/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Label } from './V1Label';
import {
    V1LabelFromJSON,
    V1LabelFromJSONTyped,
    V1LabelToJSON,
    V1LabelToJSONTyped,
} from './V1Label';

/**
 * 
 * @export
 * @interface ListLabelsForRepositoryResponse
 */
export interface ListLabelsForRepositoryResponse {
    /**
     * 
     * @type {Array<V1Label>}
     * @memberof ListLabelsForRepositoryResponse
     */
    items?: Array<V1Label>;
    /**
     * 
     * @type {string}
     * @memberof ListLabelsForRepositoryResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the ListLabelsForRepositoryResponse interface.
 */
export function instanceOfListLabelsForRepositoryResponse(value: object): value is ListLabelsForRepositoryResponse {
    return true;
}

export function ListLabelsForRepositoryResponseFromJSON(json: any): ListLabelsForRepositoryResponse {
    return ListLabelsForRepositoryResponseFromJSONTyped(json, false);
}

export function ListLabelsForRepositoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListLabelsForRepositoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(V1LabelFromJSON)),
        'nextPageToken': json['next_page_token'] == null ? undefined : json['next_page_token'],
    };
}

export function ListLabelsForRepositoryResponseToJSON(json: any): ListLabelsForRepositoryResponse {
    return ListLabelsForRepositoryResponseToJSONTyped(json, false);
}

export function ListLabelsForRepositoryResponseToJSONTyped(value?: ListLabelsForRepositoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(V1LabelToJSON)),
        'next_page_token': value['nextPageToken'],
    };
}

