/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IssueStatus } from './IssueStatus';
import {
    IssueStatusFromJSON,
    IssueStatusFromJSONTyped,
    IssueStatusToJSON,
    IssueStatusToJSONTyped,
} from './IssueStatus';

/**
 * 
 * @export
 * @interface ListIssueStatusesResponse
 */
export interface ListIssueStatusesResponse {
    /**
     * 
     * @type {string}
     * @memberof ListIssueStatusesResponse
     */
    nextPageToken?: string;
    /**
     * 
     * @type {Array<IssueStatus>}
     * @memberof ListIssueStatusesResponse
     */
    statuses?: Array<IssueStatus>;
}

/**
 * Check if a given object implements the ListIssueStatusesResponse interface.
 */
export function instanceOfListIssueStatusesResponse(value: object): value is ListIssueStatusesResponse {
    return true;
}

export function ListIssueStatusesResponseFromJSON(json: any): ListIssueStatusesResponse {
    return ListIssueStatusesResponseFromJSONTyped(json, false);
}

export function ListIssueStatusesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIssueStatusesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageToken': json['next_page_token'] == null ? undefined : json['next_page_token'],
        'statuses': json['statuses'] == null ? undefined : ((json['statuses'] as Array<any>).map(IssueStatusFromJSON)),
    };
}

export function ListIssueStatusesResponseToJSON(json: any): ListIssueStatusesResponse {
    return ListIssueStatusesResponseToJSONTyped(json, false);
}

export function ListIssueStatusesResponseToJSONTyped(value?: ListIssueStatusesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next_page_token': value['nextPageToken'],
        'statuses': value['statuses'] == null ? undefined : ((value['statuses'] as Array<any>).map(IssueStatusToJSON)),
    };
}

