/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { MergeParameters } from "./MergeParameters";
import {
    MergeParametersFromJSON,
    MergeParametersFromJSONTyped,
    MergeParametersToJSON,
    MergeParametersToJSONTyped,
} from "./MergeParameters";
import type { UserEmbedded } from "./UserEmbedded";
import {
    UserEmbeddedFromJSON,
    UserEmbeddedFromJSONTyped,
    UserEmbeddedToJSON,
    UserEmbeddedToJSONTyped,
} from "./UserEmbedded";

/**
 *
 * @export
 * @interface MergeInfo
 */
export interface MergeInfo {
    /**
     *
     * @type {string}
     * @memberof MergeInfo
     */
    error?: string;
    /**
     *
     * @type {string}
     * @memberof MergeInfo
     */
    mergeCommitHash?: string;
    /**
     *
     * @type {MergeParameters}
     * @memberof MergeInfo
     */
    mergeParameters?: MergeParameters;
    /**
     *
     * @type {UserEmbedded}
     * @memberof MergeInfo
     */
    merger?: UserEmbedded;
    /**
     *
     * @type {string}
     * @memberof MergeInfo
     */
    targetCommitHash?: string;
}

/**
 * Check if a given object implements the MergeInfo interface.
 */
export function instanceOfMergeInfo(value: object): value is MergeInfo {
    return true;
}

export function MergeInfoFromJSON(json: any): MergeInfo {
    return MergeInfoFromJSONTyped(json, false);
}

export function MergeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeInfo {
    if (json == null) {
        return json;
    }
    return {
        error: json["error"] == null ? undefined : json["error"],
        mergeCommitHash: json["merge_commit_hash"] == null ? undefined : json["merge_commit_hash"],
        mergeParameters:
            json["merge_parameters"] == null
                ? undefined
                : MergeParametersFromJSON(json["merge_parameters"]),
        merger: json["merger"] == null ? undefined : UserEmbeddedFromJSON(json["merger"]),
        targetCommitHash:
            json["target_commit_hash"] == null ? undefined : json["target_commit_hash"],
    };
}

export function MergeInfoToJSON(json: any): MergeInfo {
    return MergeInfoToJSONTyped(json, false);
}

export function MergeInfoToJSONTyped(
    value?: MergeInfo | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error: value["error"],
        merge_commit_hash: value["mergeCommitHash"],
        merge_parameters: MergeParametersToJSON(value["mergeParameters"]),
        merger: UserEmbeddedToJSON(value["merger"]),
        target_commit_hash: value["targetCommitHash"],
    };
}
