/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MilestoneEmbedded
 */
export interface MilestoneEmbedded {
    /**
     * 
     * @type {string}
     * @memberof MilestoneEmbedded
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MilestoneEmbedded
     */
    slug?: string;
}

/**
 * Check if a given object implements the MilestoneEmbedded interface.
 */
export function instanceOfMilestoneEmbedded(value: object): value is MilestoneEmbedded {
    return true;
}

export function MilestoneEmbeddedFromJSON(json: any): MilestoneEmbedded {
    return MilestoneEmbeddedFromJSONTyped(json, false);
}

export function MilestoneEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MilestoneEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function MilestoneEmbeddedToJSON(json: any): MilestoneEmbedded {
    return MilestoneEmbeddedToJSONTyped(json, false);
}

export function MilestoneEmbeddedToJSONTyped(value?: MilestoneEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
    };
}

