/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";
import type { RepositoryEmbedded } from "./RepositoryEmbedded";
import {
    RepositoryEmbeddedFromJSON,
    RepositoryEmbeddedFromJSONTyped,
    RepositoryEmbeddedToJSON,
    RepositoryEmbeddedToJSONTyped,
} from "./RepositoryEmbedded";

/**
 *
 * @export
 * @interface Ping
 */
export interface Ping {
    /**
     *
     * @type {EventHeader}
     * @memberof Ping
     */
    header?: EventHeader;
    /**
     *
     * @type {Date}
     * @memberof Ping
     */
    pingedAt?: Date;
    /**
     *
     * @type {RepositoryEmbedded}
     * @memberof Ping
     */
    repository?: RepositoryEmbedded;
    /**
     *
     * @type {string}
     * @memberof Ping
     */
    webhookSlug?: string;
}

/**
 * Check if a given object implements the Ping interface.
 */
export function instanceOfPing(value: object): value is Ping {
    return true;
}

export function PingFromJSON(json: any): Ping {
    return PingFromJSONTyped(json, false);
}

export function PingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ping {
    if (json == null) {
        return json;
    }
    return {
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        pingedAt: json["pinged_at"] == null ? undefined : new Date(json["pinged_at"]),
        repository:
            json["repository"] == null ? undefined : RepositoryEmbeddedFromJSON(json["repository"]),
        webhookSlug: json["webhook_slug"] == null ? undefined : json["webhook_slug"],
    };
}

export function PingToJSON(json: any): Ping {
    return PingToJSONTyped(json, false);
}

export function PingToJSONTyped(value?: Ping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        header: EventHeaderToJSON(value["header"]),
        pinged_at: value["pingedAt"] == null ? value["pingedAt"] : value["pingedAt"].toISOString(),
        repository: RepositoryEmbeddedToJSON(value["repository"]),
        webhook_slug: value["webhookSlug"],
    };
}
