/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProfileStatus
 */
export interface ProfileStatus {
    /**
     *
     * @type {string}
     * @memberof ProfileStatus
     */
    emoji?: string;
    /**
     *
     * @type {string}
     * @memberof ProfileStatus
     */
    message?: string;
}

/**
 * Check if a given object implements the ProfileStatus interface.
 */
export function instanceOfProfileStatus(value: object): value is ProfileStatus {
    return true;
}

export function ProfileStatusFromJSON(json: any): ProfileStatus {
    return ProfileStatusFromJSONTyped(json, false);
}

export function ProfileStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileStatus {
    if (json == null) {
        return json;
    }
    return {
        emoji: json["emoji"] == null ? undefined : json["emoji"],
        message: json["message"] == null ? undefined : json["message"],
    };
}

export function ProfileStatusToJSON(json: any): ProfileStatus {
    return ProfileStatusToJSONTyped(json, false);
}

export function ProfileStatusToJSONTyped(
    value?: ProfileStatus | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        emoji: value["emoji"],
        message: value["message"],
    };
}
