/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Cube } from "./Cube";
import { CubeFromJSON, CubeFromJSONTyped, CubeToJSON, CubeToJSONTyped } from "./Cube";

/**
 *
 * @export
 * @interface Progress
 */
export interface Progress {
    /**
     *
     * @type {Cube}
     * @memberof Progress
     */
    currentCube?: Cube;
    /**
     *
     * @type {number}
     * @memberof Progress
     */
    percent?: number;
}

/**
 * Check if a given object implements the Progress interface.
 */
export function instanceOfProgress(value: object): value is Progress {
    return true;
}

export function ProgressFromJSON(json: any): Progress {
    return ProgressFromJSONTyped(json, false);
}

export function ProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Progress {
    if (json == null) {
        return json;
    }
    return {
        currentCube: json["current_cube"] == null ? undefined : CubeFromJSON(json["current_cube"]),
        percent: json["percent"] == null ? undefined : json["percent"],
    };
}

export function ProgressToJSON(json: any): Progress {
    return ProgressToJSONTyped(json, false);
}

export function ProgressToJSONTyped(
    value?: Progress | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        current_cube: CubeToJSON(value["currentCube"]),
        percent: value["percent"],
    };
}
