/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PullRequestStatus = {
    Draft: 'draft',
    Open: 'open',
    Discarded: 'discarded',
    Merging: 'merging',
    Merged: 'merged'
} as const;
export type PullRequestStatus = typeof PullRequestStatus[keyof typeof PullRequestStatus];


export function instanceOfPullRequestStatus(value: any): boolean {
    for (const key in PullRequestStatus) {
        if (Object.prototype.hasOwnProperty.call(PullRequestStatus, key)) {
            if (PullRequestStatus[key as keyof typeof PullRequestStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PullRequestStatusFromJSON(json: any): PullRequestStatus {
    return PullRequestStatusFromJSONTyped(json, false);
}

export function PullRequestStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullRequestStatus {
    return json as PullRequestStatus;
}

export function PullRequestStatusToJSON(value?: PullRequestStatus | null): any {
    return value as any;
}

export function PullRequestStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): PullRequestStatus {
    return value as PullRequestStatus;
}

