/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Repository } from "./Repository";
import {
    RepositoryFromJSON,
    RepositoryFromJSONTyped,
    RepositoryToJSON,
    RepositoryToJSONTyped,
} from "./Repository";
import type { PullRequest } from "./PullRequest";
import {
    PullRequestFromJSON,
    PullRequestFromJSONTyped,
    PullRequestToJSON,
    PullRequestToJSONTyped,
} from "./PullRequest";
import type { PullRequestComment } from "./PullRequestComment";
import {
    PullRequestCommentFromJSON,
    PullRequestCommentFromJSONTyped,
    PullRequestCommentToJSON,
    PullRequestCommentToJSONTyped,
} from "./PullRequestComment";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";

/**
 *
 * @export
 * @interface PullRequestCommentCreateBulk
 */
export interface PullRequestCommentCreateBulk {
    /**
     *
     * @type {Array<PullRequestComment>}
     * @memberof PullRequestCommentCreateBulk
     */
    comments?: Array<PullRequestComment>;
    /**
     *
     * @type {EventHeader}
     * @memberof PullRequestCommentCreateBulk
     */
    header?: EventHeader;
    /**
     *
     * @type {PullRequest}
     * @memberof PullRequestCommentCreateBulk
     */
    pullRequest?: PullRequest;
    /**
     *
     * @type {Repository}
     * @memberof PullRequestCommentCreateBulk
     */
    repository?: Repository;
}

/**
 * Check if a given object implements the PullRequestCommentCreateBulk interface.
 */
export function instanceOfPullRequestCommentCreateBulk(
    value: object
): value is PullRequestCommentCreateBulk {
    return true;
}

export function PullRequestCommentCreateBulkFromJSON(json: any): PullRequestCommentCreateBulk {
    return PullRequestCommentCreateBulkFromJSONTyped(json, false);
}

export function PullRequestCommentCreateBulkFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): PullRequestCommentCreateBulk {
    if (json == null) {
        return json;
    }
    return {
        comments:
            json["comments"] == null
                ? undefined
                : (json["comments"] as Array<any>).map(PullRequestCommentFromJSON),
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        pullRequest:
            json["pull_request"] == null ? undefined : PullRequestFromJSON(json["pull_request"]),
        repository: json["repository"] == null ? undefined : RepositoryFromJSON(json["repository"]),
    };
}

export function PullRequestCommentCreateBulkToJSON(json: any): PullRequestCommentCreateBulk {
    return PullRequestCommentCreateBulkToJSONTyped(json, false);
}

export function PullRequestCommentCreateBulkToJSONTyped(
    value?: PullRequestCommentCreateBulk | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        comments:
            value["comments"] == null
                ? undefined
                : (value["comments"] as Array<any>).map(PullRequestCommentToJSON),
        header: EventHeaderToJSON(value["header"]),
        pull_request: PullRequestToJSON(value["pullRequest"]),
        repository: RepositoryToJSON(value["repository"]),
    };
}
