/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Repository } from "./Repository";
import {
    RepositoryFromJSON,
    RepositoryFromJSONTyped,
    RepositoryToJSON,
    RepositoryToJSONTyped,
} from "./Repository";
import type { PullRequest } from "./PullRequest";
import {
    PullRequestFromJSON,
    PullRequestFromJSONTyped,
    PullRequestToJSON,
    PullRequestToJSONTyped,
} from "./PullRequest";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";

/**
 *
 * @export
 * @interface PullRequestMergeFailure
 */
export interface PullRequestMergeFailure {
    /**
     *
     * @type {string}
     * @memberof PullRequestMergeFailure
     */
    errorMessage?: string;
    /**
     *
     * @type {EventHeader}
     * @memberof PullRequestMergeFailure
     */
    header?: EventHeader;
    /**
     *
     * @type {PullRequest}
     * @memberof PullRequestMergeFailure
     */
    pullRequest?: PullRequest;
    /**
     *
     * @type {Repository}
     * @memberof PullRequestMergeFailure
     */
    repository?: Repository;
}

/**
 * Check if a given object implements the PullRequestMergeFailure interface.
 */
export function instanceOfPullRequestMergeFailure(value: object): value is PullRequestMergeFailure {
    return true;
}

export function PullRequestMergeFailureFromJSON(json: any): PullRequestMergeFailure {
    return PullRequestMergeFailureFromJSONTyped(json, false);
}

export function PullRequestMergeFailureFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): PullRequestMergeFailure {
    if (json == null) {
        return json;
    }
    return {
        errorMessage: json["error_message"] == null ? undefined : json["error_message"],
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        pullRequest:
            json["pull_request"] == null ? undefined : PullRequestFromJSON(json["pull_request"]),
        repository: json["repository"] == null ? undefined : RepositoryFromJSON(json["repository"]),
    };
}

export function PullRequestMergeFailureToJSON(json: any): PullRequestMergeFailure {
    return PullRequestMergeFailureToJSONTyped(json, false);
}

export function PullRequestMergeFailureToJSONTyped(
    value?: PullRequestMergeFailure | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        error_message: value["errorMessage"],
        header: EventHeaderToJSON(value["header"]),
        pull_request: PullRequestToJSON(value["pullRequest"]),
        repository: RepositoryToJSON(value["repository"]),
    };
}
