/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Repository } from "./Repository";
import {
    RepositoryFromJSON,
    RepositoryFromJSONTyped,
    RepositoryToJSON,
    RepositoryToJSONTyped,
} from "./Repository";
import type { PullRequest } from "./PullRequest";
import {
    PullRequestFromJSON,
    PullRequestFromJSONTyped,
    PullRequestToJSON,
    PullRequestToJSONTyped,
} from "./PullRequest";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";

/**
 *
 * @export
 * @interface PullRequestNewIteration
 */
export interface PullRequestNewIteration {
    /**
     *
     * @type {string}
     * @memberof PullRequestNewIteration
     */
    commitSha?: string;
    /**
     *
     * @type {Date}
     * @memberof PullRequestNewIteration
     */
    createdAt?: Date;
    /**
     *
     * @type {EventHeader}
     * @memberof PullRequestNewIteration
     */
    header?: EventHeader;
    /**
     *
     * @type {string}
     * @memberof PullRequestNewIteration
     */
    mergeBaseSha?: string;
    /**
     *
     * @type {PullRequest}
     * @memberof PullRequestNewIteration
     */
    pullRequest?: PullRequest;
    /**
     *
     * @type {Repository}
     * @memberof PullRequestNewIteration
     */
    repository?: Repository;
    /**
     *
     * @type {Date}
     * @memberof PullRequestNewIteration
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the PullRequestNewIteration interface.
 */
export function instanceOfPullRequestNewIteration(value: object): value is PullRequestNewIteration {
    return true;
}

export function PullRequestNewIterationFromJSON(json: any): PullRequestNewIteration {
    return PullRequestNewIterationFromJSONTyped(json, false);
}

export function PullRequestNewIterationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): PullRequestNewIteration {
    if (json == null) {
        return json;
    }
    return {
        commitSha: json["commit_sha"] == null ? undefined : json["commit_sha"],
        createdAt: json["created_at"] == null ? undefined : new Date(json["created_at"]),
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        mergeBaseSha: json["merge_base_sha"] == null ? undefined : json["merge_base_sha"],
        pullRequest:
            json["pull_request"] == null ? undefined : PullRequestFromJSON(json["pull_request"]),
        repository: json["repository"] == null ? undefined : RepositoryFromJSON(json["repository"]),
        updatedAt: json["updated_at"] == null ? undefined : new Date(json["updated_at"]),
    };
}

export function PullRequestNewIterationToJSON(json: any): PullRequestNewIteration {
    return PullRequestNewIterationToJSONTyped(json, false);
}

export function PullRequestNewIterationToJSONTyped(
    value?: PullRequestNewIteration | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        commit_sha: value["commitSha"],
        created_at:
            value["createdAt"] == null ? value["createdAt"] : value["createdAt"].toISOString(),
        header: EventHeaderToJSON(value["header"]),
        merge_base_sha: value["mergeBaseSha"],
        pull_request: PullRequestToJSON(value["pullRequest"]),
        repository: RepositoryToJSON(value["repository"]),
        updated_at:
            value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
    };
}
