/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Repository } from "./Repository";
import {
    RepositoryFromJSON,
    RepositoryFromJSONTyped,
    RepositoryToJSON,
    RepositoryToJSONTyped,
} from "./Repository";
import type { PullRequest } from "./PullRequest";
import {
    PullRequestFromJSON,
    PullRequestFromJSONTyped,
    PullRequestToJSON,
    PullRequestToJSONTyped,
} from "./PullRequest";
import type { PullRequestComment } from "./PullRequestComment";
import {
    PullRequestCommentFromJSON,
    PullRequestCommentFromJSONTyped,
    PullRequestCommentToJSON,
    PullRequestCommentToJSONTyped,
} from "./PullRequestComment";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";
import type { Reaction } from "./Reaction";
import {
    ReactionFromJSON,
    ReactionFromJSONTyped,
    ReactionToJSON,
    ReactionToJSONTyped,
} from "./Reaction";

/**
 *
 * @export
 * @interface PullRequestCommentReactionsUpdate
 */
export interface PullRequestCommentReactionsUpdate {
    /**
     *
     * @type {Array<Reaction>}
     * @memberof PullRequestCommentReactionsUpdate
     */
    addedReactions?: Array<Reaction>;
    /**
     *
     * @type {PullRequestComment}
     * @memberof PullRequestCommentReactionsUpdate
     */
    comment?: PullRequestComment;
    /**
     *
     * @type {EventHeader}
     * @memberof PullRequestCommentReactionsUpdate
     */
    header?: EventHeader;
    /**
     *
     * @type {PullRequest}
     * @memberof PullRequestCommentReactionsUpdate
     */
    pullRequest?: PullRequest;
    /**
     *
     * @type {Array<Reaction>}
     * @memberof PullRequestCommentReactionsUpdate
     */
    removedReactions?: Array<Reaction>;
    /**
     *
     * @type {Repository}
     * @memberof PullRequestCommentReactionsUpdate
     */
    repository?: Repository;
}

/**
 * Check if a given object implements the PullRequestCommentReactionsUpdate interface.
 */
export function instanceOfPullRequestCommentReactionsUpdate(
    value: object
): value is PullRequestCommentReactionsUpdate {
    return true;
}

export function PullRequestCommentReactionsUpdateFromJSON(
    json: any
): PullRequestCommentReactionsUpdate {
    return PullRequestCommentReactionsUpdateFromJSONTyped(json, false);
}

export function PullRequestCommentReactionsUpdateFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): PullRequestCommentReactionsUpdate {
    if (json == null) {
        return json;
    }
    return {
        addedReactions:
            json["added_reactions"] == null
                ? undefined
                : (json["added_reactions"] as Array<any>).map(ReactionFromJSON),
        comment: json["comment"] == null ? undefined : PullRequestCommentFromJSON(json["comment"]),
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        pullRequest:
            json["pull_request"] == null ? undefined : PullRequestFromJSON(json["pull_request"]),
        removedReactions:
            json["removed_reactions"] == null
                ? undefined
                : (json["removed_reactions"] as Array<any>).map(ReactionFromJSON),
        repository: json["repository"] == null ? undefined : RepositoryFromJSON(json["repository"]),
    };
}

export function PullRequestCommentReactionsUpdateToJSON(
    json: any
): PullRequestCommentReactionsUpdate {
    return PullRequestCommentReactionsUpdateToJSONTyped(json, false);
}

export function PullRequestCommentReactionsUpdateToJSONTyped(
    value?: PullRequestCommentReactionsUpdate | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        added_reactions:
            value["addedReactions"] == null
                ? undefined
                : (value["addedReactions"] as Array<any>).map(ReactionToJSON),
        comment: PullRequestCommentToJSON(value["comment"]),
        header: EventHeaderToJSON(value["header"]),
        pull_request: PullRequestToJSON(value["pullRequest"]),
        removed_reactions:
            value["removedReactions"] == null
                ? undefined
                : (value["removedReactions"] as Array<any>).map(ReactionToJSON),
        repository: RepositoryToJSON(value["repository"]),
    };
}
