/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { V1ReviewerDelta } from "./V1ReviewerDelta";
import {
    V1ReviewerDeltaFromJSON,
    V1ReviewerDeltaFromJSONTyped,
    V1ReviewerDeltaToJSON,
    V1ReviewerDeltaToJSONTyped,
} from "./V1ReviewerDelta";
import type { Repository } from "./Repository";
import {
    RepositoryFromJSON,
    RepositoryFromJSONTyped,
    RepositoryToJSON,
    RepositoryToJSONTyped,
} from "./Repository";
import type { PullRequest } from "./PullRequest";
import {
    PullRequestFromJSON,
    PullRequestFromJSONTyped,
    PullRequestToJSON,
    PullRequestToJSONTyped,
} from "./PullRequest";
import type { UserEmbedded } from "./UserEmbedded";
import {
    UserEmbeddedFromJSON,
    UserEmbeddedFromJSONTyped,
    UserEmbeddedToJSON,
    UserEmbeddedToJSONTyped,
} from "./UserEmbedded";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";

/**
 *
 * @export
 * @interface PullRequestReviewAssignment
 */
export interface PullRequestReviewAssignment {
    /**
     *
     * @type {EventHeader}
     * @memberof PullRequestReviewAssignment
     */
    header?: EventHeader;
    /**
     *
     * @type {PullRequest}
     * @memberof PullRequestReviewAssignment
     */
    pullRequest?: PullRequest;
    /**
     *
     * @type {Repository}
     * @memberof PullRequestReviewAssignment
     */
    repository?: Repository;
    /**
     *
     * @type {Array<V1ReviewerDelta>}
     * @memberof PullRequestReviewAssignment
     */
    reviewerDeltas?: Array<V1ReviewerDelta>;
    /**
     *
     * @type {UserEmbedded}
     * @memberof PullRequestReviewAssignment
     */
    user?: UserEmbedded;
}

/**
 * Check if a given object implements the PullRequestReviewAssignment interface.
 */
export function instanceOfPullRequestReviewAssignment(
    value: object
): value is PullRequestReviewAssignment {
    return true;
}

export function PullRequestReviewAssignmentFromJSON(json: any): PullRequestReviewAssignment {
    return PullRequestReviewAssignmentFromJSONTyped(json, false);
}

export function PullRequestReviewAssignmentFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): PullRequestReviewAssignment {
    if (json == null) {
        return json;
    }
    return {
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        pullRequest:
            json["pull_request"] == null ? undefined : PullRequestFromJSON(json["pull_request"]),
        repository: json["repository"] == null ? undefined : RepositoryFromJSON(json["repository"]),
        reviewerDeltas:
            json["reviewer_deltas"] == null
                ? undefined
                : (json["reviewer_deltas"] as Array<any>).map(V1ReviewerDeltaFromJSON),
        user: json["user"] == null ? undefined : UserEmbeddedFromJSON(json["user"]),
    };
}

export function PullRequestReviewAssignmentToJSON(json: any): PullRequestReviewAssignment {
    return PullRequestReviewAssignmentToJSONTyped(json, false);
}

export function PullRequestReviewAssignmentToJSONTyped(
    value?: PullRequestReviewAssignment | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        header: EventHeaderToJSON(value["header"]),
        pull_request: PullRequestToJSON(value["pullRequest"]),
        repository: RepositoryToJSON(value["repository"]),
        reviewer_deltas:
            value["reviewerDeltas"] == null
                ? undefined
                : (value["reviewerDeltas"] as Array<any>).map(V1ReviewerDeltaToJSON),
        user: UserEmbeddedToJSON(value["user"]),
    };
}
