/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Repository } from "./Repository";
import {
    RepositoryFromJSON,
    RepositoryFromJSONTyped,
    RepositoryToJSON,
    RepositoryToJSONTyped,
} from "./Repository";
import type { Commit } from "./Commit";
import { CommitFromJSON, CommitFromJSONTyped, CommitToJSON, CommitToJSONTyped } from "./Commit";
import type { UserEmbedded } from "./UserEmbedded";
import {
    UserEmbeddedFromJSON,
    UserEmbeddedFromJSONTyped,
    UserEmbeddedToJSON,
    UserEmbeddedToJSONTyped,
} from "./UserEmbedded";
import type { EventHeader } from "./EventHeader";
import {
    EventHeaderFromJSON,
    EventHeaderFromJSONTyped,
    EventHeaderToJSON,
    EventHeaderToJSONTyped,
} from "./EventHeader";
import type { RefUpdate } from "./RefUpdate";
import {
    RefUpdateFromJSON,
    RefUpdateFromJSONTyped,
    RefUpdateToJSON,
    RefUpdateToJSONTyped,
} from "./RefUpdate";

/**
 *
 * @export
 * @interface Push
 */
export interface Push {
    /**
     * Commits details for this event, from before_sha to after_sha.
     * In case of tag push or new branch creation before_sha is zero
     * and commits contain only single commit.
     * @type {Array<Commit>}
     * @memberof Push
     */
    commits?: Array<Commit>;
    /**
     *
     * @type {string}
     * @memberof Push
     */
    defaultBranch?: string;
    /**
     *
     * @type {boolean}
     * @memberof Push
     */
    hasMoreCommits?: boolean;
    /**
     *
     * @type {EventHeader}
     * @memberof Push
     */
    header?: EventHeader;
    /**
     *
     * @type {boolean}
     * @memberof Push
     */
    isDefaultBranchUpdated?: boolean;
    /**
     *
     * @type {Date}
     * @memberof Push
     */
    pushedAt?: Date;
    /**
     *
     * @type {UserEmbedded}
     * @memberof Push
     */
    pusher?: UserEmbedded;
    /**
     *
     * @type {RefUpdate}
     * @memberof Push
     */
    refUpdate?: RefUpdate;
    /**
     *
     * @type {Repository}
     * @memberof Push
     */
    repository?: Repository;
}

/**
 * Check if a given object implements the Push interface.
 */
export function instanceOfPush(value: object): value is Push {
    return true;
}

export function PushFromJSON(json: any): Push {
    return PushFromJSONTyped(json, false);
}

export function PushFromJSONTyped(json: any, ignoreDiscriminator: boolean): Push {
    if (json == null) {
        return json;
    }
    return {
        commits:
            json["commits"] == null
                ? undefined
                : (json["commits"] as Array<any>).map(CommitFromJSON),
        defaultBranch: json["default_branch"] == null ? undefined : json["default_branch"],
        hasMoreCommits: json["has_more_commits"] == null ? undefined : json["has_more_commits"],
        header: json["header"] == null ? undefined : EventHeaderFromJSON(json["header"]),
        isDefaultBranchUpdated:
            json["is_default_branch_updated"] == null
                ? undefined
                : json["is_default_branch_updated"],
        pushedAt: json["pushed_at"] == null ? undefined : new Date(json["pushed_at"]),
        pusher: json["pusher"] == null ? undefined : UserEmbeddedFromJSON(json["pusher"]),
        refUpdate: json["ref_update"] == null ? undefined : RefUpdateFromJSON(json["ref_update"]),
        repository: json["repository"] == null ? undefined : RepositoryFromJSON(json["repository"]),
    };
}

export function PushToJSON(json: any): Push {
    return PushToJSONTyped(json, false);
}

export function PushToJSONTyped(value?: Push | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        commits:
            value["commits"] == null
                ? undefined
                : (value["commits"] as Array<any>).map(CommitToJSON),
        default_branch: value["defaultBranch"],
        has_more_commits: value["hasMoreCommits"],
        header: EventHeaderToJSON(value["header"]),
        is_default_branch_updated: value["isDefaultBranchUpdated"],
        pushed_at: value["pushedAt"] == null ? value["pushedAt"] : value["pushedAt"].toISOString(),
        pusher: UserEmbeddedToJSON(value["pusher"]),
        ref_update: RefUpdateToJSON(value["refUpdate"]),
        repository: RepositoryToJSON(value["repository"]),
    };
}
