/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReactionCount } from './ReactionCount';
import {
    ReactionCountFromJSON,
    ReactionCountFromJSONTyped,
    ReactionCountToJSON,
    ReactionCountToJSONTyped,
} from './ReactionCount';

/**
 * 
 * @export
 * @interface Reactions
 */
export interface Reactions {
    /**
     * 
     * @type {{ [key: string]: ReactionCount; }}
     * @memberof Reactions
     */
    reactions?: { [key: string]: ReactionCount; };
}

/**
 * Check if a given object implements the Reactions interface.
 */
export function instanceOfReactions(value: object): value is Reactions {
    return true;
}

export function ReactionsFromJSON(json: any): Reactions {
    return ReactionsFromJSONTyped(json, false);
}

export function ReactionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reactions {
    if (json == null) {
        return json;
    }
    return {
        
        'reactions': json['reactions'] == null ? undefined : (mapValues(json['reactions'], ReactionCountFromJSON)),
    };
}

export function ReactionsToJSON(json: any): Reactions {
    return ReactionsToJSONTyped(json, false);
}

export function ReactionsToJSONTyped(value?: Reactions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reactions': value['reactions'] == null ? undefined : (mapValues(value['reactions'], ReactionCountToJSON)),
    };
}

