/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Reaction = {
    Like: "like",
    Dislike: "dislike",
    Heart: "heart",
    CheckMark: "check_mark",
    Eyes: "eyes",
    Fire: "fire",
    VictoryHand: "victory_hand",
    HeartEyes: "heart_eyes",
    HundredPoints: "hundred_points",
    PartyPopper: "party_popper",
    PartyFace: "party_face",
    RollingEyes: "rolling_eyes",
    Fist: "fist",
    ClappingHands: "clapping_hands",
    ThinkingFace: "thinking_face",
    NeutralFace: "neutral_face",
    WinkingFace: "winking_face",
    OpenMouth: "open_mouth",
    Shrug: "shrug",
    PleadingFace: "pleading_face",
    ConfusedFace: "confused_face",
    SmilingFace: "smiling_face",
    Sunglasses: "sunglasses",
    Rocket: "rocket",
    Robot: "robot",
    Goose: "goose",
} as const;
export type Reaction = (typeof Reaction)[keyof typeof Reaction];

export function instanceOfReaction(value: any): boolean {
    for (const key in Reaction) {
        if (Object.prototype.hasOwnProperty.call(Reaction, key)) {
            if (Reaction[key as keyof typeof Reaction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReactionFromJSON(json: any): Reaction {
    return ReactionFromJSONTyped(json, false);
}

export function ReactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reaction {
    return json as Reaction;
}

export function ReactionToJSON(value?: Reaction | null): any {
    return value as any;
}

export function ReactionToJSONTyped(value: any, ignoreDiscriminator: boolean): Reaction {
    return value as Reaction;
}
