/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RefUpdateOperation } from "./RefUpdateOperation";
import {
    RefUpdateOperationFromJSON,
    RefUpdateOperationFromJSONTyped,
    RefUpdateOperationToJSON,
    RefUpdateOperationToJSONTyped,
} from "./RefUpdateOperation";

/**
 *
 * @export
 * @interface RefUpdate
 */
export interface RefUpdate {
    /**
     *
     * @type {string}
     * @memberof RefUpdate
     */
    afterSha?: string;
    /**
     *
     * @type {string}
     * @memberof RefUpdate
     */
    beforeSha?: string;
    /**
     *
     * @type {string}
     * @memberof RefUpdate
     */
    checkoutSha?: string;
    /**
     *
     * @type {RefUpdateOperation}
     * @memberof RefUpdate
     */
    operation?: RefUpdateOperation;
    /**
     *
     * @type {string}
     * @memberof RefUpdate
     */
    ref?: string;
}

/**
 * Check if a given object implements the RefUpdate interface.
 */
export function instanceOfRefUpdate(value: object): value is RefUpdate {
    return true;
}

export function RefUpdateFromJSON(json: any): RefUpdate {
    return RefUpdateFromJSONTyped(json, false);
}

export function RefUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefUpdate {
    if (json == null) {
        return json;
    }
    return {
        afterSha: json["after_sha"] == null ? undefined : json["after_sha"],
        beforeSha: json["before_sha"] == null ? undefined : json["before_sha"],
        checkoutSha: json["checkout_sha"] == null ? undefined : json["checkout_sha"],
        operation:
            json["operation"] == null ? undefined : RefUpdateOperationFromJSON(json["operation"]),
        ref: json["ref"] == null ? undefined : json["ref"],
    };
}

export function RefUpdateToJSON(json: any): RefUpdate {
    return RefUpdateToJSONTyped(json, false);
}

export function RefUpdateToJSONTyped(
    value?: RefUpdate | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        after_sha: value["afterSha"],
        before_sha: value["beforeSha"],
        checkout_sha: value["checkoutSha"],
        operation: RefUpdateOperationToJSON(value["operation"]),
        ref: value["ref"],
    };
}
