/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const RefUpdateOperation = {
    Create: "create",
    Update: "update",
    Delete: "delete",
} as const;
export type RefUpdateOperation = (typeof RefUpdateOperation)[keyof typeof RefUpdateOperation];

export function instanceOfRefUpdateOperation(value: any): boolean {
    for (const key in RefUpdateOperation) {
        if (Object.prototype.hasOwnProperty.call(RefUpdateOperation, key)) {
            if (RefUpdateOperation[key as keyof typeof RefUpdateOperation] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RefUpdateOperationFromJSON(json: any): RefUpdateOperation {
    return RefUpdateOperationFromJSONTyped(json, false);
}

export function RefUpdateOperationFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): RefUpdateOperation {
    return json as RefUpdateOperation;
}

export function RefUpdateOperationToJSON(value?: RefUpdateOperation | null): any {
    return value as any;
}

export function RefUpdateOperationToJSONTyped(
    value: any,
    ignoreDiscriminator: boolean
): RefUpdateOperation {
    return value as RefUpdateOperation;
}
