/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ReleaseStatus = {
    Draft: "draft",
    Published: "published",
    Discarded: "discarded",
} as const;
export type ReleaseStatus = (typeof ReleaseStatus)[keyof typeof ReleaseStatus];

export function instanceOfReleaseStatus(value: any): boolean {
    for (const key in ReleaseStatus) {
        if (Object.prototype.hasOwnProperty.call(ReleaseStatus, key)) {
            if (ReleaseStatus[key as keyof typeof ReleaseStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReleaseStatusFromJSON(json: any): ReleaseStatus {
    return ReleaseStatusFromJSONTyped(json, false);
}

export function ReleaseStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseStatus {
    return json as ReleaseStatus;
}

export function ReleaseStatusToJSON(value?: ReleaseStatus | null): any {
    return value as any;
}

export function ReleaseStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ReleaseStatus {
    return value as ReleaseStatus;
}
