/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ReleaseAsset } from "./ReleaseAsset";
import {
    ReleaseAssetFromJSON,
    ReleaseAssetFromJSONTyped,
    ReleaseAssetToJSON,
    ReleaseAssetToJSONTyped,
} from "./ReleaseAsset";
import type { ReleaseStatus } from "./ReleaseStatus";
import {
    ReleaseStatusFromJSON,
    ReleaseStatusFromJSONTyped,
    ReleaseStatusToJSON,
    ReleaseStatusToJSONTyped,
} from "./ReleaseStatus";
import type { UserEmbedded } from "./UserEmbedded";
import {
    UserEmbeddedFromJSON,
    UserEmbeddedFromJSONTyped,
    UserEmbeddedToJSON,
    UserEmbeddedToJSONTyped,
} from "./UserEmbedded";

/**
 *
 * @export
 * @interface Release
 */
export interface Release {
    /**
     *
     * @type {Array<ReleaseAsset>}
     * @memberof Release
     */
    assets?: Array<ReleaseAsset>;
    /**
     *
     * @type {UserEmbedded}
     * @memberof Release
     */
    author?: UserEmbedded;
    /**
     *
     * @type {Date}
     * @memberof Release
     */
    createdAt?: Date;
    /**
     *
     * @type {string}
     * @memberof Release
     */
    hash?: string;
    /**
     *
     * @type {string}
     * @memberof Release
     */
    id?: string;
    /**
     *
     * @type {boolean}
     * @memberof Release
     */
    isLatest?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Release
     */
    isPreRelease?: boolean;
    /**
     *
     * @type {string}
     * @memberof Release
     */
    releaseNotes?: string;
    /**
     *
     * @type {Date}
     * @memberof Release
     */
    releasedAt?: Date;
    /**
     *
     * @type {string}
     * @memberof Release
     */
    repoId?: string;
    /**
     *
     * @type {ReleaseStatus}
     * @memberof Release
     */
    status?: ReleaseStatus;
    /**
     *
     * @type {string}
     * @memberof Release
     */
    tag?: string;
    /**
     *
     * @type {string}
     * @memberof Release
     */
    title?: string;
    /**
     *
     * @type {Date}
     * @memberof Release
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the Release interface.
 */
export function instanceOfRelease(value: object): value is Release {
    return true;
}

export function ReleaseFromJSON(json: any): Release {
    return ReleaseFromJSONTyped(json, false);
}

export function ReleaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Release {
    if (json == null) {
        return json;
    }
    return {
        assets:
            json["assets"] == null
                ? undefined
                : (json["assets"] as Array<any>).map(ReleaseAssetFromJSON),
        author: json["author"] == null ? undefined : UserEmbeddedFromJSON(json["author"]),
        createdAt: json["created_at"] == null ? undefined : new Date(json["created_at"]),
        hash: json["hash"] == null ? undefined : json["hash"],
        id: json["id"] == null ? undefined : json["id"],
        isLatest: json["is_latest"] == null ? undefined : json["is_latest"],
        isPreRelease: json["is_pre_release"] == null ? undefined : json["is_pre_release"],
        releaseNotes: json["release_notes"] == null ? undefined : json["release_notes"],
        releasedAt: json["released_at"] == null ? undefined : new Date(json["released_at"]),
        repoId: json["repo_id"] == null ? undefined : json["repo_id"],
        status: json["status"] == null ? undefined : ReleaseStatusFromJSON(json["status"]),
        tag: json["tag"] == null ? undefined : json["tag"],
        title: json["title"] == null ? undefined : json["title"],
        updatedAt: json["updated_at"] == null ? undefined : new Date(json["updated_at"]),
    };
}

export function ReleaseToJSON(json: any): Release {
    return ReleaseToJSONTyped(json, false);
}

export function ReleaseToJSONTyped(
    value?: Release | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        assets:
            value["assets"] == null
                ? undefined
                : (value["assets"] as Array<any>).map(ReleaseAssetToJSON),
        author: UserEmbeddedToJSON(value["author"]),
        created_at:
            value["createdAt"] == null ? value["createdAt"] : value["createdAt"].toISOString(),
        hash: value["hash"],
        id: value["id"],
        is_latest: value["isLatest"],
        is_pre_release: value["isPreRelease"],
        release_notes: value["releaseNotes"],
        released_at:
            value["releasedAt"] == null ? value["releasedAt"] : value["releasedAt"].toISOString(),
        repo_id: value["repoId"],
        status: ReleaseStatusToJSON(value["status"]),
        tag: value["tag"],
        title: value["title"],
        updated_at:
            value["updatedAt"] == null ? value["updatedAt"] : value["updatedAt"].toISOString(),
    };
}
