/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SubjectRole } from "./SubjectRole";
import {
    SubjectRoleFromJSON,
    SubjectRoleFromJSONTyped,
    SubjectRoleToJSON,
    SubjectRoleToJSONTyped,
} from "./SubjectRole";

/**
 *
 * @export
 * @interface RemoveRepoRolesResponse
 */
export interface RemoveRepoRolesResponse {
    /**
     * A token, which can be sent as `page_token` to retrieve the next page.
     * If this field is omitted, there are no subsequent pages.
     * @type {string}
     * @memberof RemoveRepoRolesResponse
     */
    nextPageToken?: string;
    /**
     *
     * @type {Array<SubjectRole>}
     * @memberof RemoveRepoRolesResponse
     */
    subjectRoles?: Array<SubjectRole>;
}

/**
 * Check if a given object implements the RemoveRepoRolesResponse interface.
 */
export function instanceOfRemoveRepoRolesResponse(value: object): value is RemoveRepoRolesResponse {
    return true;
}

export function RemoveRepoRolesResponseFromJSON(json: any): RemoveRepoRolesResponse {
    return RemoveRepoRolesResponseFromJSONTyped(json, false);
}

export function RemoveRepoRolesResponseFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): RemoveRepoRolesResponse {
    if (json == null) {
        return json;
    }
    return {
        nextPageToken: json["next_page_token"] == null ? undefined : json["next_page_token"],
        subjectRoles:
            json["subject_roles"] == null
                ? undefined
                : (json["subject_roles"] as Array<any>).map(SubjectRoleFromJSON),
    };
}

export function RemoveRepoRolesResponseToJSON(json: any): RemoveRepoRolesResponse {
    return RemoveRepoRolesResponseToJSONTyped(json, false);
}

export function RemoveRepoRolesResponseToJSONTyped(
    value?: RemoveRepoRolesResponse | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        next_page_token: value["nextPageToken"],
        subject_roles:
            value["subjectRoles"] == null
                ? undefined
                : (value["subjectRoles"] as Array<any>).map(SubjectRoleToJSON),
    };
}
