/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SubjectRole } from "./SubjectRole";
import {
    SubjectRoleFromJSON,
    SubjectRoleFromJSONTyped,
    SubjectRoleToJSON,
    SubjectRoleToJSONTyped,
} from "./SubjectRole";

/**
 *
 * @export
 * @interface RemoveRepoRolesBody
 */
export interface RemoveRepoRolesBody {
    /**
     *
     * @type {Array<SubjectRole>}
     * @memberof RemoveRepoRolesBody
     */
    subjectRoles?: Array<SubjectRole>;
}

/**
 * Check if a given object implements the RemoveRepoRolesBody interface.
 */
export function instanceOfRemoveRepoRolesBody(value: object): value is RemoveRepoRolesBody {
    return true;
}

export function RemoveRepoRolesBodyFromJSON(json: any): RemoveRepoRolesBody {
    return RemoveRepoRolesBodyFromJSONTyped(json, false);
}

export function RemoveRepoRolesBodyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): RemoveRepoRolesBody {
    if (json == null) {
        return json;
    }
    return {
        subjectRoles:
            json["subject_roles"] == null
                ? undefined
                : (json["subject_roles"] as Array<any>).map(SubjectRoleFromJSON),
    };
}

export function RemoveRepoRolesBodyToJSON(json: any): RemoveRepoRolesBody {
    return RemoveRepoRolesBodyToJSONTyped(json, false);
}

export function RemoveRepoRolesBodyToJSONTyped(
    value?: RemoveRepoRolesBody | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        subject_roles:
            value["subjectRoles"] == null
                ? undefined
                : (value["subjectRoles"] as Array<any>).map(SubjectRoleToJSON),
    };
}
