/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WorkflowInput } from "./WorkflowInput";
import {
    WorkflowInputFromJSON,
    WorkflowInputFromJSONTyped,
    WorkflowInputToJSON,
    WorkflowInputToJSONTyped,
} from "./WorkflowInput";

/**
 *
 * @export
 * @interface RunCIBody
 */
export interface RunCIBody {
    /**
     *
     * @type {WorkflowInput}
     * @memberof RunCIBody
     */
    input?: WorkflowInput;
    /**
     *
     * @type {string}
     * @memberof RunCIBody
     */
    revision?: string;
    /**
     *
     * @type {string}
     * @memberof RunCIBody
     */
    workflowRevision?: string;
}

/**
 * Check if a given object implements the RunCIBody interface.
 */
export function instanceOfRunCIBody(value: object): value is RunCIBody {
    return true;
}

export function RunCIBodyFromJSON(json: any): RunCIBody {
    return RunCIBodyFromJSONTyped(json, false);
}

export function RunCIBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunCIBody {
    if (json == null) {
        return json;
    }
    return {
        input: json["input"] == null ? undefined : WorkflowInputFromJSON(json["input"]),
        revision: json["revision"] == null ? undefined : json["revision"],
        workflowRevision: json["workflow_revision"] == null ? undefined : json["workflow_revision"],
    };
}

export function RunCIBodyToJSON(json: any): RunCIBody {
    return RunCIBodyToJSONTyped(json, false);
}

export function RunCIBodyToJSONTyped(
    value?: RunCIBody | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        input: WorkflowInputToJSON(value["input"]),
        revision: value["revision"],
        workflow_revision: value["workflowRevision"],
    };
}
