/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *  - prepared: Status `prepared` may only appear as a Run status.
 * It's a stage between creation and startup during which the Run is populated with workflows.
 * @export
 */
export const RunStatus = {
    Created: "created",
    Prepared: "prepared",
    Processing: "processing",
    Success: "success",
    Failed: "failed",
    Canceled: "canceled",
    Timeout: "timeout",
} as const;
export type RunStatus = (typeof RunStatus)[keyof typeof RunStatus];

export function instanceOfRunStatus(value: any): boolean {
    for (const key in RunStatus) {
        if (Object.prototype.hasOwnProperty.call(RunStatus, key)) {
            if (RunStatus[key as keyof typeof RunStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RunStatusFromJSON(json: any): RunStatus {
    return RunStatusFromJSONTyped(json, false);
}

export function RunStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunStatus {
    return json as RunStatus;
}

export function RunStatusToJSON(value?: RunStatus | null): any {
    return value as any;
}

export function RunStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RunStatus {
    return value as RunStatus;
}
