/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const StatusType = {
    Initial: "initial",
    InProgress: "in_progress",
    Paused: "paused",
    Completed: "completed",
    Cancelled: "cancelled",
} as const;
export type StatusType = (typeof StatusType)[keyof typeof StatusType];

export function instanceOfStatusType(value: any): boolean {
    for (const key in StatusType) {
        if (Object.prototype.hasOwnProperty.call(StatusType, key)) {
            if (StatusType[key as keyof typeof StatusType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusTypeFromJSON(json: any): StatusType {
    return StatusTypeFromJSONTyped(json, false);
}

export function StatusTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusType {
    return json as StatusType;
}

export function StatusTypeToJSON(value?: StatusType | null): any {
    return value as any;
}

export function StatusTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusType {
    return value as StatusType;
}
