/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const SubjectType = {
    User: "user",
} as const;
export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];

export function instanceOfSubjectType(value: any): boolean {
    for (const key in SubjectType) {
        if (Object.prototype.hasOwnProperty.call(SubjectType, key)) {
            if (SubjectType[key as keyof typeof SubjectType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubjectTypeFromJSON(json: any): SubjectType {
    return SubjectTypeFromJSONTyped(json, false);
}

export function SubjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectType {
    return json as SubjectType;
}

export function SubjectTypeToJSON(value?: SubjectType | null): any {
    return value as any;
}

export function SubjectTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SubjectType {
    return value as SubjectType;
}
