/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DatesByStage } from "./DatesByStage";
import {
    DatesByStageFromJSON,
    DatesByStageFromJSONTyped,
    DatesByStageToJSON,
    DatesByStageToJSONTyped,
} from "./DatesByStage";
import type { Progress } from "./Progress";
import {
    ProgressFromJSON,
    ProgressFromJSONTyped,
    ProgressToJSON,
    ProgressToJSONTyped,
} from "./Progress";
import type { Cube } from "./Cube";
import { CubeFromJSON, CubeFromJSONTyped, CubeToJSON, CubeToJSONTyped } from "./Cube";
import type { RunStatus } from "./RunStatus";
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from "./RunStatus";
import type { Relations } from "./Relations";
import {
    RelationsFromJSON,
    RelationsFromJSONTyped,
    RelationsToJSON,
    RelationsToJSONTyped,
} from "./Relations";

/**
 *
 * @export
 * @interface Task
 */
export interface Task {
    /**
     *
     * @type {Array<Cube>}
     * @memberof Task
     */
    cubes?: Array<Cube>;
    /**
     *
     * @type {DatesByStage}
     * @memberof Task
     */
    dates?: DatesByStage;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    id?: string;
    /**
     *
     * @type {Progress}
     * @memberof Task
     */
    progress?: Progress;
    /**
     *
     * @type {Relations}
     * @memberof Task
     */
    relations?: Relations;
    /**
     *
     * @type {string}
     * @memberof Task
     */
    slug?: string;
    /**
     *
     * @type {RunStatus}
     * @memberof Task
     */
    status?: RunStatus;
}

/**
 * Check if a given object implements the Task interface.
 */
export function instanceOfTask(value: object): value is Task {
    return true;
}

export function TaskFromJSON(json: any): Task {
    return TaskFromJSONTyped(json, false);
}

export function TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): Task {
    if (json == null) {
        return json;
    }
    return {
        cubes: json["cubes"] == null ? undefined : (json["cubes"] as Array<any>).map(CubeFromJSON),
        dates: json["dates"] == null ? undefined : DatesByStageFromJSON(json["dates"]),
        description: json["description"] == null ? undefined : json["description"],
        id: json["id"] == null ? undefined : json["id"],
        progress: json["progress"] == null ? undefined : ProgressFromJSON(json["progress"]),
        relations: json["relations"] == null ? undefined : RelationsFromJSON(json["relations"]),
        slug: json["slug"] == null ? undefined : json["slug"],
        status: json["status"] == null ? undefined : RunStatusFromJSON(json["status"]),
    };
}

export function TaskToJSON(json: any): Task {
    return TaskToJSONTyped(json, false);
}

export function TaskToJSONTyped(value?: Task | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        cubes: value["cubes"] == null ? undefined : (value["cubes"] as Array<any>).map(CubeToJSON),
        dates: DatesByStageToJSON(value["dates"]),
        description: value["description"],
        id: value["id"],
        progress: ProgressToJSON(value["progress"]),
        relations: RelationsToJSON(value["relations"]),
        slug: value["slug"],
        status: RunStatusToJSON(value["status"]),
    };
}
