/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatingOptions
 */
export interface TemplatingOptions {
    /**
     * 
     * @type {string}
     * @memberof TemplatingOptions
     */
    templateId?: string;
}

/**
 * Check if a given object implements the TemplatingOptions interface.
 */
export function instanceOfTemplatingOptions(value: object): value is TemplatingOptions {
    return true;
}

export function TemplatingOptionsFromJSON(json: any): TemplatingOptions {
    return TemplatingOptionsFromJSONTyped(json, false);
}

export function TemplatingOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatingOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
    };
}

export function TemplatingOptionsToJSON(json: any): TemplatingOptions {
    return TemplatingOptionsToJSONTyped(json, false);
}

export function TemplatingOptionsToJSONTyped(value?: TemplatingOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'template_id': value['templateId'],
    };
}

