/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePullRequestBody
 */
export interface UpdatePullRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdatePullRequestBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePullRequestBody
     */
    title?: string;
}

/**
 * Check if a given object implements the UpdatePullRequestBody interface.
 */
export function instanceOfUpdatePullRequestBody(value: object): value is UpdatePullRequestBody {
    return true;
}

export function UpdatePullRequestBodyFromJSON(json: any): UpdatePullRequestBody {
    return UpdatePullRequestBodyFromJSONTyped(json, false);
}

export function UpdatePullRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePullRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function UpdatePullRequestBodyToJSON(json: any): UpdatePullRequestBody {
    return UpdatePullRequestBodyToJSONTyped(json, false);
}

export function UpdatePullRequestBodyToJSONTyped(value?: UpdatePullRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'title': value['title'],
    };
}

