/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateReleaseBody
 */
export interface UpdateReleaseBody {
    /**
     *
     * @type {string}
     * @memberof UpdateReleaseBody
     */
    releaseNotes?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateReleaseBody
     */
    title?: string;
}

/**
 * Check if a given object implements the UpdateReleaseBody interface.
 */
export function instanceOfUpdateReleaseBody(value: object): value is UpdateReleaseBody {
    return true;
}

export function UpdateReleaseBodyFromJSON(json: any): UpdateReleaseBody {
    return UpdateReleaseBodyFromJSONTyped(json, false);
}

export function UpdateReleaseBodyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateReleaseBody {
    if (json == null) {
        return json;
    }
    return {
        releaseNotes: json["release_notes"] == null ? undefined : json["release_notes"],
        title: json["title"] == null ? undefined : json["title"],
    };
}

export function UpdateReleaseBodyToJSON(json: any): UpdateReleaseBody {
    return UpdateReleaseBodyToJSONTyped(json, false);
}

export function UpdateReleaseBodyToJSONTyped(
    value?: UpdateReleaseBody | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        release_notes: value["releaseNotes"],
        title: value["title"],
    };
}
