/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PRReviewer } from './PRReviewer';
import {
    PRReviewerFromJSON,
    PRReviewerFromJSONTyped,
    PRReviewerToJSON,
    PRReviewerToJSONTyped,
} from './PRReviewer';

/**
 * 
 * @export
 * @interface UpdateReviewersResponse
 */
export interface UpdateReviewersResponse {
    /**
     * 
     * @type {Array<PRReviewer>}
     * @memberof UpdateReviewersResponse
     */
    reviewers?: Array<PRReviewer>;
}

/**
 * Check if a given object implements the UpdateReviewersResponse interface.
 */
export function instanceOfUpdateReviewersResponse(value: object): value is UpdateReviewersResponse {
    return true;
}

export function UpdateReviewersResponseFromJSON(json: any): UpdateReviewersResponse {
    return UpdateReviewersResponseFromJSONTyped(json, false);
}

export function UpdateReviewersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateReviewersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewers': json['reviewers'] == null ? undefined : ((json['reviewers'] as Array<any>).map(PRReviewerFromJSON)),
    };
}

export function UpdateReviewersResponseToJSON(json: any): UpdateReviewersResponse {
    return UpdateReviewersResponseToJSONTyped(json, false);
}

export function UpdateReviewersResponseToJSONTyped(value?: UpdateReviewersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reviewers': value['reviewers'] == null ? undefined : ((value['reviewers'] as Array<any>).map(PRReviewerToJSON)),
    };
}

