/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UpdateLabelBody
 */
export interface UpdateLabelBody {
    /**
     *
     * @type {string}
     * @memberof UpdateLabelBody
     */
    color?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateLabelBody
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof UpdateLabelBody
     */
    slug?: string;
}

/**
 * Check if a given object implements the UpdateLabelBody interface.
 */
export function instanceOfUpdateLabelBody(value: object): value is UpdateLabelBody {
    return true;
}

export function UpdateLabelBodyFromJSON(json: any): UpdateLabelBody {
    return UpdateLabelBodyFromJSONTyped(json, false);
}

export function UpdateLabelBodyFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): UpdateLabelBody {
    if (json == null) {
        return json;
    }
    return {
        color: json["color"] == null ? undefined : json["color"],
        name: json["name"] == null ? undefined : json["name"],
        slug: json["slug"] == null ? undefined : json["slug"],
    };
}

export function UpdateLabelBodyToJSON(json: any): UpdateLabelBody {
    return UpdateLabelBodyToJSONTyped(json, false);
}

export function UpdateLabelBodyToJSONTyped(
    value?: UpdateLabelBody | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        color: value["color"],
        name: value["name"],
        slug: value["slug"],
    };
}
