/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserEmbedded
 */
export interface UserEmbedded {
    /**
     *
     * @type {string}
     * @memberof UserEmbedded
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof UserEmbedded
     */
    slug?: string;
}

/**
 * Check if a given object implements the UserEmbedded interface.
 */
export function instanceOfUserEmbedded(value: object): value is UserEmbedded {
    return true;
}

export function UserEmbeddedFromJSON(json: any): UserEmbedded {
    return UserEmbeddedFromJSONTyped(json, false);
}

export function UserEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEmbedded {
    if (json == null) {
        return json;
    }
    return {
        id: json["id"] == null ? undefined : json["id"],
        slug: json["slug"] == null ? undefined : json["slug"],
    };
}

export function UserEmbeddedToJSON(json: any): UserEmbedded {
    return UserEmbeddedToJSONTyped(json, false);
}

export function UserEmbeddedToJSONTyped(
    value?: UserEmbedded | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: value["id"],
        slug: value["slug"],
    };
}
