/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Timezone } from "./Timezone";
import {
    TimezoneFromJSON,
    TimezoneFromJSONTyped,
    TimezoneToJSON,
    TimezoneToJSONTyped,
} from "./Timezone";
import type { ProfileVisibility } from "./ProfileVisibility";
import {
    ProfileVisibilityFromJSON,
    ProfileVisibilityFromJSONTyped,
    ProfileVisibilityToJSON,
    ProfileVisibilityToJSONTyped,
} from "./ProfileVisibility";
import type { ProfileStatus } from "./ProfileStatus";
import {
    ProfileStatusFromJSON,
    ProfileStatusFromJSONTyped,
    ProfileStatusToJSON,
    ProfileStatusToJSONTyped,
} from "./ProfileStatus";
import type { Workplace } from "./Workplace";
import {
    WorkplaceFromJSON,
    WorkplaceFromJSONTyped,
    WorkplaceToJSON,
    WorkplaceToJSONTyped,
} from "./Workplace";
import type { Image } from "./Image";
import { ImageFromJSON, ImageFromJSONTyped, ImageToJSON, ImageToJSONTyped } from "./Image";
import type { Link } from "./Link";
import { LinkFromJSON, LinkFromJSONTyped, LinkToJSON, LinkToJSONTyped } from "./Link";
import type { V1Location } from "./V1Location";
import {
    V1LocationFromJSON,
    V1LocationFromJSONTyped,
    V1LocationToJSON,
    V1LocationToJSONTyped,
} from "./V1Location";

/**
 *
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     *
     * @type {Image}
     * @memberof UserProfile
     */
    avatar?: Image;
    /**
     *
     * @type {Image}
     * @memberof UserProfile
     */
    backgroundImage?: Image;
    /**
     *
     * @type {string}
     * @memberof UserProfile
     */
    bio?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfile
     */
    displayName?: string;
    /**
     *
     * @type {string}
     * @memberof UserProfile
     */
    id?: string;
    /**
     *
     * @type {Array<Link>}
     * @memberof UserProfile
     */
    links?: Array<Link>;
    /**
     *
     * @type {V1Location}
     * @memberof UserProfile
     */
    location?: V1Location;
    /**
     *
     * @type {ProfileStatus}
     * @memberof UserProfile
     */
    status?: ProfileStatus;
    /**
     *
     * @type {Timezone}
     * @memberof UserProfile
     */
    timezone?: Timezone;
    /**
     *
     * @type {string}
     * @memberof UserProfile
     */
    username?: string;
    /**
     *
     * @type {ProfileVisibility}
     * @memberof UserProfile
     */
    visibility?: ProfileVisibility;
    /**
     *
     * @type {Workplace}
     * @memberof UserProfile
     */
    workplace?: Workplace;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        avatar: json["avatar"] == null ? undefined : ImageFromJSON(json["avatar"]),
        backgroundImage:
            json["background_image"] == null ? undefined : ImageFromJSON(json["background_image"]),
        bio: json["bio"] == null ? undefined : json["bio"],
        displayName: json["display_name"] == null ? undefined : json["display_name"],
        id: json["id"] == null ? undefined : json["id"],
        links: json["links"] == null ? undefined : (json["links"] as Array<any>).map(LinkFromJSON),
        location: json["location"] == null ? undefined : V1LocationFromJSON(json["location"]),
        status: json["status"] == null ? undefined : ProfileStatusFromJSON(json["status"]),
        timezone: json["timezone"] == null ? undefined : TimezoneFromJSON(json["timezone"]),
        username: json["username"] == null ? undefined : json["username"],
        visibility:
            json["visibility"] == null ? undefined : ProfileVisibilityFromJSON(json["visibility"]),
        workplace: json["workplace"] == null ? undefined : WorkplaceFromJSON(json["workplace"]),
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(
    value?: UserProfile | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        avatar: ImageToJSON(value["avatar"]),
        background_image: ImageToJSON(value["backgroundImage"]),
        bio: value["bio"],
        display_name: value["displayName"],
        id: value["id"],
        links: value["links"] == null ? undefined : (value["links"] as Array<any>).map(LinkToJSON),
        location: V1LocationToJSON(value["location"]),
        status: ProfileStatusToJSON(value["status"]),
        timezone: TimezoneToJSON(value["timezone"]),
        username: value["username"],
        visibility: ProfileVisibilityToJSON(value["visibility"]),
        workplace: WorkplaceToJSON(value["workplace"]),
    };
}
