/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Commit } from "./Commit";
import { CommitFromJSON, CommitFromJSONTyped, CommitToJSON, CommitToJSONTyped } from "./Commit";

/**
 *
 * @export
 * @interface V1Tag
 */
export interface V1Tag {
    /**
     *
     * @type {Commit}
     * @memberof V1Tag
     */
    commit?: Commit;
    /**
     *
     * @type {string}
     * @memberof V1Tag
     */
    message?: string;
    /**
     *
     * @type {string}
     * @memberof V1Tag
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof V1Tag
     */
    target?: string;
}

/**
 * Check if a given object implements the V1Tag interface.
 */
export function instanceOfV1Tag(value: object): value is V1Tag {
    return true;
}

export function V1TagFromJSON(json: any): V1Tag {
    return V1TagFromJSONTyped(json, false);
}

export function V1TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Tag {
    if (json == null) {
        return json;
    }
    return {
        commit: json["commit"] == null ? undefined : CommitFromJSON(json["commit"]),
        message: json["message"] == null ? undefined : json["message"],
        name: json["name"] == null ? undefined : json["name"],
        target: json["target"] == null ? undefined : json["target"],
    };
}

export function V1TagToJSON(json: any): V1Tag {
    return V1TagToJSONTyped(json, false);
}

export function V1TagToJSONTyped(value?: V1Tag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        commit: CommitToJSON(value["commit"]),
        message: value["message"],
        name: value["name"],
        target: value["target"],
    };
}
