/* tslint:disable */
/* eslint-disable */
/**
 * SourceCraft API
 * Bleeding edge of Public REST API of SourceCraft
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: info@sourcecraft.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DatesByStage } from "./DatesByStage";
import {
    DatesByStageFromJSON,
    DatesByStageFromJSONTyped,
    DatesByStageToJSON,
    DatesByStageToJSONTyped,
} from "./DatesByStage";
import type { Progress } from "./Progress";
import {
    ProgressFromJSON,
    ProgressFromJSONTyped,
    ProgressToJSON,
    ProgressToJSONTyped,
} from "./Progress";
import type { Task } from "./Task";
import { TaskFromJSON, TaskFromJSONTyped, TaskToJSON, TaskToJSONTyped } from "./Task";
import type { RunStatus } from "./RunStatus";
import {
    RunStatusFromJSON,
    RunStatusFromJSONTyped,
    RunStatusToJSON,
    RunStatusToJSONTyped,
} from "./RunStatus";

/**
 *
 * @export
 * @interface Workflow
 */
export interface Workflow {
    /**
     *
     * @type {DatesByStage}
     * @memberof Workflow
     */
    dates?: DatesByStage;
    /**
     *
     * @type {string}
     * @memberof Workflow
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof Workflow
     */
    id?: string;
    /**
     *
     * @type {Progress}
     * @memberof Workflow
     */
    progress?: Progress;
    /**
     *
     * @type {string}
     * @memberof Workflow
     */
    slug?: string;
    /**
     *
     * @type {RunStatus}
     * @memberof Workflow
     */
    status?: RunStatus;
    /**
     *
     * @type {Array<Task>}
     * @memberof Workflow
     */
    tasks?: Array<Task>;
}

/**
 * Check if a given object implements the Workflow interface.
 */
export function instanceOfWorkflow(value: object): value is Workflow {
    return true;
}

export function WorkflowFromJSON(json: any): Workflow {
    return WorkflowFromJSONTyped(json, false);
}

export function WorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workflow {
    if (json == null) {
        return json;
    }
    return {
        dates: json["dates"] == null ? undefined : DatesByStageFromJSON(json["dates"]),
        description: json["description"] == null ? undefined : json["description"],
        id: json["id"] == null ? undefined : json["id"],
        progress: json["progress"] == null ? undefined : ProgressFromJSON(json["progress"]),
        slug: json["slug"] == null ? undefined : json["slug"],
        status: json["status"] == null ? undefined : RunStatusFromJSON(json["status"]),
        tasks: json["tasks"] == null ? undefined : (json["tasks"] as Array<any>).map(TaskFromJSON),
    };
}

export function WorkflowToJSON(json: any): Workflow {
    return WorkflowToJSONTyped(json, false);
}

export function WorkflowToJSONTyped(
    value?: Workflow | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        dates: DatesByStageToJSON(value["dates"]),
        description: value["description"],
        id: value["id"],
        progress: ProgressToJSON(value["progress"]),
        slug: value["slug"],
        status: RunStatusToJSON(value["status"]),
        tasks: value["tasks"] == null ? undefined : (value["tasks"] as Array<any>).map(TaskToJSON),
    };
}
